<template><div><p>打开idea，选择创建项目：<br /><img src="https://cdn.nlark.com/yuque/0/2022/png/2725910/1650965173099-99806cac-f3ed-4f51-8739-f591f466bc69.png#clientId=u25870090-c119-4&amp;crop=0&amp;crop=0&amp;crop=1&amp;crop=1&amp;from=paste&amp;height=695&amp;id=u87a94d5f&amp;margin=[object Object]&amp;name=image.png&amp;originHeight=869&amp;originWidth=1080&amp;originalType=binary&amp;ratio=1&amp;rotation=0&amp;showTitle=false&amp;size=145975&amp;status=done&amp;style=none&amp;taskId=u65d605db-7432-4900-9813-9af8dcc5454&amp;title=&amp;width=864" alt="image.png" loading="lazy"><br />设置好后点击下一步：<br /><img src="https://cdn.nlark.com/yuque/0/2022/png/2725910/1650965205618-7a102012-02d1-4db5-9df1-d1678d47027a.png#clientId=u25870090-c119-4&amp;crop=0&amp;crop=0&amp;crop=1&amp;crop=1&amp;from=paste&amp;height=695&amp;id=u1614919f&amp;margin=[object Object]&amp;name=image.png&amp;originHeight=869&amp;originWidth=1080&amp;originalType=binary&amp;ratio=1&amp;rotation=0&amp;showTitle=false&amp;size=144602&amp;status=done&amp;style=none&amp;taskId=u82f89536-8cf4-45d6-a9a8-3635e2bf6ac&amp;title=&amp;width=864" alt="image.png" loading="lazy"><br />选择spring web之后点击创建：<br /><img src="https://cdn.nlark.com/yuque/0/2022/png/2725910/1650965245417-747cb22d-9e6e-4b0f-b703-ef0b39f0896d.png#clientId=u25870090-c119-4&amp;crop=0&amp;crop=0&amp;crop=1&amp;crop=1&amp;from=paste&amp;height=590&amp;id=u8a111f88&amp;margin=[object Object]&amp;name=image.png&amp;originHeight=738&amp;originWidth=486&amp;originalType=binary&amp;ratio=1&amp;rotation=0&amp;showTitle=false&amp;size=65852&amp;status=done&amp;style=none&amp;taskId=uf603b0d2-e5df-447f-bd2c-e0619fa301c&amp;title=&amp;width=388.8" alt="image.png" loading="lazy"><br />项目结构如上，然后右键pom.xml选择maven-&gt;创建setting.xml并打开该文件，在文件中添加阿里云源，解决依赖下载失败的问题。<br />setting.xml：</p>
<div class="language-xml ext-xml line-numbers-mode"><pre v-pre class="language-xml"><code><span class="token prolog">&lt;?xml version="1.0" encoding="UTF-8"?></span>
<span class="token tag"><span class="token tag"><span class="token punctuation">&lt;</span>settings</span> <span class="token attr-name">xmlns</span><span class="token attr-value"><span class="token punctuation attr-equals">=</span><span class="token punctuation">"</span>http://maven.apache.org/SETTINGS/1.0.0<span class="token punctuation">"</span></span>
          <span class="token attr-name"><span class="token namespace">xmlns:</span>xsi</span><span class="token attr-value"><span class="token punctuation attr-equals">=</span><span class="token punctuation">"</span>http://www.w3.org/2001/XMLSchema-instance<span class="token punctuation">"</span></span>
          <span class="token attr-name"><span class="token namespace">xsi:</span>schemaLocation</span><span class="token attr-value"><span class="token punctuation attr-equals">=</span><span class="token punctuation">"</span>http://maven.apache.org/SETTINGS/1.0.0 http://maven.apache.org/xsd/settings-1.0.0.xsd<span class="token punctuation">"</span></span><span class="token punctuation">></span></span>
    <span class="token tag"><span class="token tag"><span class="token punctuation">&lt;</span>mirrors</span><span class="token punctuation">></span></span>
        <span class="token tag"><span class="token tag"><span class="token punctuation">&lt;</span>mirror</span><span class="token punctuation">></span></span>
            <span class="token tag"><span class="token tag"><span class="token punctuation">&lt;</span>id</span><span class="token punctuation">></span></span>alimaven<span class="token tag"><span class="token tag"><span class="token punctuation">&lt;/</span>id</span><span class="token punctuation">></span></span>
            <span class="token tag"><span class="token tag"><span class="token punctuation">&lt;</span>name</span><span class="token punctuation">></span></span>aliyun maven<span class="token tag"><span class="token tag"><span class="token punctuation">&lt;/</span>name</span><span class="token punctuation">></span></span>
            <span class="token tag"><span class="token tag"><span class="token punctuation">&lt;</span>url</span><span class="token punctuation">></span></span>http://maven.aliyun.com/nexus/content/groups/public/<span class="token tag"><span class="token tag"><span class="token punctuation">&lt;/</span>url</span><span class="token punctuation">></span></span>
            <span class="token tag"><span class="token tag"><span class="token punctuation">&lt;</span>mirrorOf</span><span class="token punctuation">></span></span>central<span class="token tag"><span class="token tag"><span class="token punctuation">&lt;/</span>mirrorOf</span><span class="token punctuation">></span></span>
        <span class="token tag"><span class="token tag"><span class="token punctuation">&lt;/</span>mirror</span><span class="token punctuation">></span></span>
    <span class="token tag"><span class="token tag"><span class="token punctuation">&lt;/</span>mirrors</span><span class="token punctuation">></span></span>

<span class="token tag"><span class="token tag"><span class="token punctuation">&lt;/</span>settings</span><span class="token punctuation">></span></span>
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><p>然后在com.example.MyShop包下面创建HelloController类，并添加如下内容：</p>
<div class="language-java ext-java line-numbers-mode"><pre v-pre class="language-java"><code><span class="token keyword">package</span> <span class="token namespace">com<span class="token punctuation">.</span>example<span class="token punctuation">.</span>myshop</span><span class="token punctuation">;</span>


<span class="token keyword">import</span> <span class="token import"><span class="token namespace">org<span class="token punctuation">.</span>springframework<span class="token punctuation">.</span>web<span class="token punctuation">.</span>bind<span class="token punctuation">.</span>annotation<span class="token punctuation">.</span></span><span class="token class-name">RequestMapping</span></span><span class="token punctuation">;</span>
<span class="token keyword">import</span> <span class="token import"><span class="token namespace">org<span class="token punctuation">.</span>springframework<span class="token punctuation">.</span>web<span class="token punctuation">.</span>bind<span class="token punctuation">.</span>annotation<span class="token punctuation">.</span></span><span class="token class-name">RestController</span></span><span class="token punctuation">;</span>

<span class="token annotation punctuation">@RestController</span>
<span class="token keyword">public</span> <span class="token keyword">class</span> <span class="token class-name">HelloController</span> <span class="token punctuation">{</span>
    <span class="token annotation punctuation">@RequestMapping</span><span class="token punctuation">(</span><span class="token string">"/hello"</span><span class="token punctuation">)</span>
    <span class="token keyword">public</span> <span class="token class-name">String</span> <span class="token function">hello</span><span class="token punctuation">(</span><span class="token punctuation">)</span> <span class="token punctuation">{</span>
        <span class="token keyword">return</span> <span class="token string">"Hello Spring Boot!"</span><span class="token punctuation">;</span>
    <span class="token punctuation">}</span>
<span class="token punctuation">}</span>

</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><p>右键项目运行类启动项目：<br /><img src="https://cdn.nlark.com/yuque/0/2022/png/2725910/1650965547466-ec920c80-277e-4718-9b70-583d2ec2fec6.png#clientId=u25870090-c119-4&amp;crop=0&amp;crop=0&amp;crop=1&amp;crop=1&amp;from=paste&amp;height=125&amp;id=uf815d371&amp;margin=[object Object]&amp;name=image.png&amp;originHeight=156&amp;originWidth=416&amp;originalType=binary&amp;ratio=1&amp;rotation=0&amp;showTitle=false&amp;size=16618&amp;status=done&amp;style=none&amp;taskId=ue96c0917-92cb-4df1-9e81-be917b83199&amp;title=&amp;width=332.8" alt="image.png" loading="lazy"><br />输出如下：<br /><img src="https://cdn.nlark.com/yuque/0/2022/png/2725910/1650965618659-3042c713-6a49-42ae-872c-2d2c24dfad5e.png#clientId=u25870090-c119-4&amp;crop=0&amp;crop=0&amp;crop=1&amp;crop=1&amp;from=paste&amp;height=622&amp;id=ubda2077e&amp;margin=[object Object]&amp;name=image.png&amp;originHeight=778&amp;originWidth=1802&amp;originalType=binary&amp;ratio=1&amp;rotation=0&amp;showTitle=false&amp;size=213158&amp;status=done&amp;style=none&amp;taskId=u1691ea5a-4cbc-45b3-939d-5d515fcc6b6&amp;title=&amp;width=1441.6" alt="image.png" loading="lazy"><br />访问127.0.0.1:8080/hello：<br /><img src="https://cdn.nlark.com/yuque/0/2022/png/2725910/1650965657384-63272590-06c7-43e7-a358-7de8b822cbad.png#clientId=u25870090-c119-4&amp;crop=0&amp;crop=0&amp;crop=1&amp;crop=1&amp;from=paste&amp;height=174&amp;id=uc41c2a66&amp;margin=[object Object]&amp;name=image.png&amp;originHeight=218&amp;originWidth=526&amp;originalType=binary&amp;ratio=1&amp;rotation=0&amp;showTitle=false&amp;size=18618&amp;status=done&amp;style=none&amp;taskId=u4c433cde-b28c-404a-9eb7-0595e7efe1e&amp;title=&amp;width=420.8" alt="image.png" loading="lazy"><br />项目创建成功。</p>
</div></template>


