<template><div><p><a name="8c915c07"></a></p>
<h2 id="c语言函数调用栈" tabindex="-1"><a class="header-anchor" href="#c语言函数调用栈" aria-hidden="true">#</a> C语言函数调用栈</h2>
<p>测试程序：</p>
<div class="language-c ext-c line-numbers-mode"><pre v-pre class="language-c"><code><span class="token macro property"><span class="token directive-hash">#</span><span class="token directive keyword">include</span><span class="token string">&lt;stdio.h></span></span>
<span class="token keyword">int</span> <span class="token function">sum</span><span class="token punctuation">(</span><span class="token keyword">int</span> x<span class="token punctuation">,</span><span class="token keyword">int</span> y<span class="token punctuation">)</span><span class="token punctuation">{</span>
        <span class="token keyword">int</span> a<span class="token operator">=</span>x<span class="token operator">+</span>y<span class="token punctuation">;</span>
        <span class="token keyword">return</span> a<span class="token punctuation">;</span>
<span class="token punctuation">}</span>
<span class="token keyword">int</span> <span class="token function">main</span><span class="token punctuation">(</span><span class="token punctuation">)</span><span class="token punctuation">{</span>
        <span class="token function">sum</span><span class="token punctuation">(</span><span class="token number">1</span><span class="token punctuation">,</span><span class="token number">2</span><span class="token punctuation">)</span><span class="token punctuation">;</span>
        <span class="token keyword">return</span> <span class="token number">0</span><span class="token punctuation">;</span>
<span class="token punctuation">}</span>
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><p>编译指令</p>
<div class="language-text ext-text line-numbers-mode"><pre v-pre class="language-text"><code>gcc -m32 test.c -o test
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div></div></div><p>32位ida反汇编之后：<br />main函数：<br /><img src="https://img-blog.csdnimg.cn/20210221130147817.png?x-oss-process=image/watermark,type_ZmFuZ3poZW5naGVpdGk,shadow_10,text_aHR0cHM6Ly9ibG9nLmNzZG4ubmV0L3dlaXhpbl80NTk0MzUyMg==,size_16,color_FFFFFF,t_70#pic_center#crop=0&amp;crop=0&amp;crop=1&amp;crop=1&amp;id=MKk0I&amp;originHeight=322&amp;originWidth=752&amp;originalType=binary&amp;ratio=1&amp;rotation=0&amp;showTitle=false&amp;status=done&amp;style=none&amp;title=" alt="" loading="lazy"></p>
<p>sum函数：<br /><img src="https://img-blog.csdnimg.cn/20210221130212306.png?x-oss-process=image/watermark,type_ZmFuZ3poZW5naGVpdGk,shadow_10,text_aHR0cHM6Ly9ibG9nLmNzZG4ubmV0L3dlaXhpbl80NTk0MzUyMg==,size_16,color_FFFFFF,t_70#pic_center#crop=0&amp;crop=0&amp;crop=1&amp;crop=1&amp;id=JpYlw&amp;originHeight=301&amp;originWidth=775&amp;originalType=binary&amp;ratio=1&amp;rotation=0&amp;showTitle=false&amp;status=done&amp;style=none&amp;title=" alt="" loading="lazy"></p>
<p><a name="06fb5a5a"></a></p>
<h3 id="汇编指令" tabindex="-1"><a class="header-anchor" href="#汇编指令" aria-hidden="true">#</a> 汇编指令：</h3>
<p><strong>push ebp</strong>：将ebp寄存器中的值压入栈中<br /><strong>pop esi</strong> ：将栈中的数据放入esi寄存器中<br /><strong>call</strong> ：<br />将当前的指令指针EIP(该指针指向紧接在call指令后的下条指令)压入堆栈，以备返回时能恢复执行下条指令；然后设置EIP指向被调函数代码开始处，以跳转到被调函数的入口地址执行。<br /><strong>leave</strong>：<br />恢复主调函数的栈帧以准备返回。等价于指令序列movl esp，ebp(恢复原ESP值，指向被调函数栈帧开始处)和pop ebp(恢复原ebp的值，即主调函数帧基指针)。<br /><strong>ret</strong>：<br />与call指令配合，用于从函数或过程返回。从栈顶弹出返回地址(之前call指令保存的下条指令地址)到EIP寄存器中，程序转到该地址处继续执行(此时ESP指向进入函数时的第一个参数)。若带立即数，ESP再加立即数(丢弃一些在执行call前入栈的参数)。使用该指令前，应使当前栈顶指针所指向位置的内容正好是先前call指令保存的返回地址。</p>
<p><a name="74316853"></a></p>
<h3 id="测试程序调用sum函数过程" tabindex="-1"><a class="header-anchor" href="#测试程序调用sum函数过程" aria-hidden="true">#</a> 测试程序调用sum函数过程：</h3>
<p><a name="fde657e7"></a></p>
<h4 id="首先-将参数压入栈中" tabindex="-1"><a class="header-anchor" href="#首先-将参数压入栈中" aria-hidden="true">#</a> 首先：将参数压入栈中</h4>
<p><img src="https://img-blog.csdnimg.cn/2021022113031569.png?x-oss-process=image/watermark,type_ZmFuZ3poZW5naGVpdGk,shadow_10,text_aHR0cHM6Ly9ibG9nLmNzZG4ubmV0L3dlaXhpbl80NTk0MzUyMg==,size_16,color_FFFFFF,t_70#pic_center#crop=0&amp;crop=0&amp;crop=1&amp;crop=1&amp;id=ChcXq&amp;originHeight=432&amp;originWidth=901&amp;originalType=binary&amp;ratio=1&amp;rotation=0&amp;showTitle=false&amp;status=done&amp;style=none&amp;title=" alt="" loading="lazy"></p>
<p>可以观察到我们传入的参数是sum（1，2）；调用函数时是逆序压栈，即2先入栈，然后是1，由于栈是后入先出结构，所以参数1在栈顶，先出栈。<br />再来看寄存器，此时push 2指令还未执行，所以eip寄存器中存放的地址是push 2指令的地址，即cpu将要执行的指令。此时栈底指针ebp和栈顶指针esp指向同一个位置，即当前栈帧为空。<br />最后看栈结构，<br /><img src="https://img-blog.csdnimg.cn/20210221130357898.png?x-oss-process=image/watermark,type_ZmFuZ3poZW5naGVpdGk,shadow_10,text_aHR0cHM6Ly9ibG9nLmNzZG4ubmV0L3dlaXhpbl80NTk0MzUyMg==,size_16,color_FFFFFF,t_70#pic_center#crop=0&amp;crop=0&amp;crop=1&amp;crop=1&amp;id=dAObE&amp;originHeight=369&amp;originWidth=769&amp;originalType=binary&amp;ratio=1&amp;rotation=0&amp;showTitle=false&amp;status=done&amp;style=none&amp;title=" alt="" loading="lazy"><img src="https://img-blog.csdnimg.cn/20210221130441915.png?x-oss-process=image/watermark,type_ZmFuZ3poZW5naGVpdGk,shadow_10,text_aHR0cHM6Ly9ibG9nLmNzZG4ubmV0L3dlaXhpbl80NTk0MzUyMg==,size_16,color_FFFFFF,t_70#pic_center#crop=0&amp;crop=0&amp;crop=1&amp;crop=1&amp;id=nBcTo&amp;originHeight=586&amp;originWidth=817&amp;originalType=binary&amp;ratio=1&amp;rotation=0&amp;showTitle=false&amp;status=done&amp;style=none&amp;title=" alt="" loading="lazy"><br /><img src="https://img-blog.csdnimg.cn/20210221130520319.png#pic_center#crop=0&amp;crop=0&amp;crop=1&amp;crop=1&amp;id=tP1jU&amp;originHeight=88&amp;originWidth=552&amp;originalType=binary&amp;ratio=1&amp;rotation=0&amp;showTitle=false&amp;status=done&amp;style=none&amp;title=" alt="" loading="lazy"></p>
<p><a name="21ad25c7"></a></p>
<h4 id="接下来执行call-sum指令" tabindex="-1"><a class="header-anchor" href="#接下来执行call-sum指令" aria-hidden="true">#</a> 接下来执行call sum指令</h4>
<p>call指令是将call sum指令的下一条指令的地址（即指令add esp，8的地址【0x565561eb】）入栈，然后将sum函数的第一条指令的地址放入eip寄存器中。<br /><img src="https://img-blog.csdnimg.cn/20210221130557361.png?x-oss-process=image/watermark,type_ZmFuZ3poZW5naGVpdGk,shadow_10,text_aHR0cHM6Ly9ibG9nLmNzZG4ubmV0L3dlaXhpbl80NTk0MzUyMg==,size_16,color_FFFFFF,t_70#pic_center#crop=0&amp;crop=0&amp;crop=1&amp;crop=1&amp;id=PDQgW&amp;originHeight=532&amp;originWidth=780&amp;originalType=binary&amp;ratio=1&amp;rotation=0&amp;showTitle=false&amp;status=done&amp;style=none&amp;title=" alt="" loading="lazy"></p>
<p>此时栈的结构：<br /><img src="https://img-blog.csdnimg.cn/20210221130621867.png?x-oss-process=image/watermark,type_ZmFuZ3poZW5naGVpdGk,shadow_10,text_aHR0cHM6Ly9ibG9nLmNzZG4ubmV0L3dlaXhpbl80NTk0MzUyMg==,size_16,color_FFFFFF,t_70#pic_center#crop=0&amp;crop=0&amp;crop=1&amp;crop=1&amp;id=fMI63&amp;originHeight=324&amp;originWidth=491&amp;originalType=binary&amp;ratio=1&amp;rotation=0&amp;showTitle=false&amp;status=done&amp;style=none&amp;title=" alt="" loading="lazy"></p>
<p><a name="bff6ff6c"></a></p>
<h4 id="进入sum函数" tabindex="-1"><a class="header-anchor" href="#进入sum函数" aria-hidden="true">#</a> 进入sum函数：</h4>
<p><img src="https://img-blog.csdnimg.cn/20210221130646717.png#pic_center#crop=0&amp;crop=0&amp;crop=1&amp;crop=1&amp;id=Ek8v8&amp;originHeight=65&amp;originWidth=553&amp;originalType=binary&amp;ratio=1&amp;rotation=0&amp;showTitle=false&amp;status=done&amp;style=none&amp;title=" alt="" loading="lazy"></p>
<p>这两条指令的目的是为sum函数创建新的栈帧<br />首先，push ebp，即ebp寄存器的值（ 0xffffd2c8）入栈</p>
<p><img src="https://img-blog.csdnimg.cn/20210221130714718.png?x-oss-process=image/watermark,type_ZmFuZ3poZW5naGVpdGk,shadow_10,text_aHR0cHM6Ly9ibG9nLmNzZG4ubmV0L3dlaXhpbl80NTk0MzUyMg==,size_16,color_FFFFFF,t_70#pic_center#crop=0&amp;crop=0&amp;crop=1&amp;crop=1&amp;id=mERtr&amp;originHeight=558&amp;originWidth=727&amp;originalType=binary&amp;ratio=1&amp;rotation=0&amp;showTitle=false&amp;status=done&amp;style=none&amp;title=" alt="" loading="lazy"><br /><img src="https://img-blog.csdnimg.cn/20210221130822772.png?x-oss-process=image/watermark,type_ZmFuZ3poZW5naGVpdGk,shadow_10,text_aHR0cHM6Ly9ibG9nLmNzZG4ubmV0L3dlaXhpbl80NTk0MzUyMg==,size_16,color_FFFFFF,t_70#pic_center#crop=0&amp;crop=0&amp;crop=1&amp;crop=1&amp;id=VAYwl&amp;originHeight=372&amp;originWidth=829&amp;originalType=binary&amp;ratio=1&amp;rotation=0&amp;showTitle=false&amp;status=done&amp;style=none&amp;title=" alt="" loading="lazy"></p>
<p>然后mov ebp，esp，即把esp寄存器的值赋给ebp。<br /><img src="https://img-blog.csdnimg.cn/20210221130852961.png?x-oss-process=image/watermark,type_ZmFuZ3poZW5naGVpdGk,shadow_10,text_aHR0cHM6Ly9ibG9nLmNzZG4ubmV0L3dlaXhpbl80NTk0MzUyMg==,size_16,color_FFFFFF,t_70#pic_center#crop=0&amp;crop=0&amp;crop=1&amp;crop=1&amp;id=FTqrK&amp;originHeight=558&amp;originWidth=790&amp;originalType=binary&amp;ratio=1&amp;rotation=0&amp;showTitle=false&amp;status=done&amp;style=none&amp;title=" alt="" loading="lazy"><br /><img src="https://img-blog.csdnimg.cn/20210221130915413.png?x-oss-process=image/watermark,type_ZmFuZ3poZW5naGVpdGk,shadow_10,text_aHR0cHM6Ly9ibG9nLmNzZG4ubmV0L3dlaXhpbl80NTk0MzUyMg==,size_16,color_FFFFFF,t_70#pic_center#crop=0&amp;crop=0&amp;crop=1&amp;crop=1&amp;id=OqkKZ&amp;originHeight=384&amp;originWidth=843&amp;originalType=binary&amp;ratio=1&amp;rotation=0&amp;showTitle=false&amp;status=done&amp;style=none&amp;title=" alt="" loading="lazy"></p>
<p><a name="ba540fb3"></a></p>
<h4 id="离开sum函数" tabindex="-1"><a class="header-anchor" href="#离开sum函数" aria-hidden="true">#</a> 离开sum函数</h4>
<p>中间经过了一系列的指令后，接下来离开sum函数，需要执行leave，ret指令。<br />leave执行前（因为执行了sum函数里的其他指令，所以此时栈的内容有些看不明白）：<br /><img src="https://img-blog.csdnimg.cn/20210221130946287.png?x-oss-process=image/watermark,type_ZmFuZ3poZW5naGVpdGk,shadow_10,text_aHR0cHM6Ly9ibG9nLmNzZG4ubmV0L3dlaXhpbl80NTk0MzUyMg==,size_16,color_FFFFFF,t_70#pic_center#crop=0&amp;crop=0&amp;crop=1&amp;crop=1&amp;id=k3xPv&amp;originHeight=636&amp;originWidth=891&amp;originalType=binary&amp;ratio=1&amp;rotation=0&amp;showTitle=false&amp;status=done&amp;style=none&amp;title=" alt="" loading="lazy"></p>
<p><img src="https://img-blog.csdnimg.cn/20210221131009234.png?x-oss-process=image/watermark,type_ZmFuZ3poZW5naGVpdGk,shadow_10,text_aHR0cHM6Ly9ibG9nLmNzZG4ubmV0L3dlaXhpbl80NTk0MzUyMg==,size_16,color_FFFFFF,t_70#pic_center#crop=0&amp;crop=0&amp;crop=1&amp;crop=1&amp;id=bCpyg&amp;originHeight=732&amp;originWidth=468&amp;originalType=binary&amp;ratio=1&amp;rotation=0&amp;showTitle=false&amp;status=done&amp;style=none&amp;title=" alt="" loading="lazy"></p>
<p>执行leave函数：即将ebp的值赋给esp，然后将先前存入栈中的ebp的值取出放入当前ebp寄存器中。</p>
<p><img src="https://img-blog.csdnimg.cn/20210221131034187.png?x-oss-process=image/watermark,type_ZmFuZ3poZW5naGVpdGk,shadow_10,text_aHR0cHM6Ly9ibG9nLmNzZG4ubmV0L3dlaXhpbl80NTk0MzUyMg==,size_16,color_FFFFFF,t_70#pic_center#crop=0&amp;crop=0&amp;crop=1&amp;crop=1&amp;id=F1Om5&amp;originHeight=578&amp;originWidth=830&amp;originalType=binary&amp;ratio=1&amp;rotation=0&amp;showTitle=false&amp;status=done&amp;style=none&amp;title=" alt="" loading="lazy"><br /><img src="https://img-blog.csdnimg.cn/20210221131054939.png?x-oss-process=image/watermark,type_ZmFuZ3poZW5naGVpdGk,shadow_10,text_aHR0cHM6Ly9ibG9nLmNzZG4ubmV0L3dlaXhpbl80NTk0MzUyMg==,size_16,color_FFFFFF,t_70#pic_center#crop=0&amp;crop=0&amp;crop=1&amp;crop=1&amp;id=SWKCo&amp;originHeight=543&amp;originWidth=978&amp;originalType=binary&amp;ratio=1&amp;rotation=0&amp;showTitle=false&amp;status=done&amp;style=none&amp;title=" alt="" loading="lazy"></p>
<p>然后执行ret指令，将先前存入栈中的eip的值放入当前eip寄存器中。</p>
<p><img src="https://img-blog.csdnimg.cn/2021022113111635.png?x-oss-process=image/watermark,type_ZmFuZ3poZW5naGVpdGk,shadow_10,text_aHR0cHM6Ly9ibG9nLmNzZG4ubmV0L3dlaXhpbl80NTk0MzUyMg==,size_16,color_FFFFFF,t_70#pic_center#crop=0&amp;crop=0&amp;crop=1&amp;crop=1&amp;id=AImiI&amp;originHeight=617&amp;originWidth=928&amp;originalType=binary&amp;ratio=1&amp;rotation=0&amp;showTitle=false&amp;status=done&amp;style=none&amp;title=" alt="" loading="lazy"><br /><img src="https://img-blog.csdnimg.cn/202102211311391.png?x-oss-process=image/watermark,type_ZmFuZ3poZW5naGVpdGk,shadow_10,text_aHR0cHM6Ly9ibG9nLmNzZG4ubmV0L3dlaXhpbl80NTk0MzUyMg==,size_16,color_FFFFFF,t_70#pic_center#crop=0&amp;crop=0&amp;crop=1&amp;crop=1&amp;id=WyNqB&amp;originHeight=546&amp;originWidth=892&amp;originalType=binary&amp;ratio=1&amp;rotation=0&amp;showTitle=false&amp;status=done&amp;style=none&amp;title=" alt="" loading="lazy"></p>
<p><a name="1fce024b"></a></p>
<h4 id="回到主函数" tabindex="-1"><a class="header-anchor" href="#回到主函数" aria-hidden="true">#</a> 回到主函数：</h4>
<p>离开之后，回到主函数，执行add esp，8指令（即call sum指令的下一条指令），因为栈是从高地址向低地址方向增长，将栈顶指针esp的值加8，即把栈顶往栈底压，相当于把先前放入栈中的参数1，2移除。<br /><img src="https://img-blog.csdnimg.cn/20210221131212211.png?x-oss-process=image/watermark,type_ZmFuZ3poZW5naGVpdGk,shadow_10,text_aHR0cHM6Ly9ibG9nLmNzZG4ubmV0L3dlaXhpbl80NTk0MzUyMg==,size_16,color_FFFFFF,t_70#pic_center#crop=0&amp;crop=0&amp;crop=1&amp;crop=1&amp;id=rTYxo&amp;originHeight=509&amp;originWidth=923&amp;originalType=binary&amp;ratio=1&amp;rotation=0&amp;showTitle=false&amp;status=done&amp;style=none&amp;title=" alt="" loading="lazy"><br /><img src="https://img-blog.csdnimg.cn/20210221131229801.png?x-oss-process=image/watermark,type_ZmFuZ3poZW5naGVpdGk,shadow_10,text_aHR0cHM6Ly9ibG9nLmNzZG4ubmV0L3dlaXhpbl80NTk0MzUyMg==,size_16,color_FFFFFF,t_70#pic_center#crop=0&amp;crop=0&amp;crop=1&amp;crop=1&amp;id=PQJIm&amp;originHeight=428&amp;originWidth=706&amp;originalType=binary&amp;ratio=1&amp;rotation=0&amp;showTitle=false&amp;status=done&amp;style=none&amp;title=" alt="" loading="lazy"></p>
<p>可以发现，此时的栈结构与调用sum函数前没有区别。<br /><img src="https://img-blog.csdnimg.cn/20210221131254244.png?x-oss-process=image/watermark,type_ZmFuZ3poZW5naGVpdGk,shadow_10,text_aHR0cHM6Ly9ibG9nLmNzZG4ubmV0L3dlaXhpbl80NTk0MzUyMg==,size_16,color_FFFFFF,t_70#pic_center#crop=0&amp;crop=0&amp;crop=1&amp;crop=1&amp;id=CGVHp&amp;originHeight=710&amp;originWidth=368&amp;originalType=binary&amp;ratio=1&amp;rotation=0&amp;showTitle=false&amp;status=done&amp;style=none&amp;title=" alt="" loading="lazy"></p>
<p><a name="d3bbef50"></a></p>
<h4 id="完整过程" tabindex="-1"><a class="header-anchor" href="#完整过程" aria-hidden="true">#</a> 完整过程：</h4>
<p><img src="https://img-blog.csdnimg.cn/20210221131313650.png?x-oss-process=image/watermark,type_ZmFuZ3poZW5naGVpdGk,shadow_10,text_aHR0cHM6Ly9ibG9nLmNzZG4ubmV0L3dlaXhpbl80NTk0MzUyMg==,size_16,color_FFFFFF,t_70#pic_center#crop=0&amp;crop=0&amp;crop=1&amp;crop=1&amp;id=PVwMy&amp;originHeight=663&amp;originWidth=1191&amp;originalType=binary&amp;ratio=1&amp;rotation=0&amp;showTitle=false&amp;status=done&amp;style=none&amp;title=" alt="" loading="lazy"></p>
</div></template>


