import { sidebar } from "vuepress-theme-hope";

export const enSidebar = sidebar({
  "/": [
    "",
    {
      text: "java",
      icon: "tip",
      link: "java/",
      prefix: "java/",
      collapsable: true,
      children: [
          "01.Java学习路线",
          "02.函数式编程-Stream流",
      ],
    },
    {
      text: "LeetCode",
      icon: "tip",
      link: "leetcode/",
      prefix: "leetcode/",
      collapsable: true,
      children: "structure",
    },
    {
      text: "常用框架",
      icon: "tip",
      link: "framework/",
      prefix: "framework/",
      collapsable: true,
      children: "structure",
    },
    {
      text: "数据库",
      icon: "tip",
      link: "database/",
      prefix: "database/",
      collapsable: true,
      children: [
          "01.NoSQL数据库简介",
          "02.Redis概述安装",
          "03.常用的五大数据类型",
          "04.Redis配置文件介绍",
          "05.Redis的发布和订阅",
          "06.Redis新数据类型",
          "07.Redis_Jedis_测试",
          "08.Redis_Jedis_实例",
          "09.Redis与Spring Boot整合",
          "10.Redis_事务_锁机制_秒杀",
          "11.Redis_事务_秒杀案例",
          "12.Redis持久化之RDB",
          "13.Redis持久化之AOF",
          "14.Redis_主从复制",
          "15.Redis集群",
          "16.Redis应用问题解决",
      ],
    },
    {
      text: "计算机基础",
      icon: "tip",
      link: "basics/",
      prefix: "basics/",
      collapsable: true,
      children: "structure",
    },
    {
      text: "常用工具",
      icon: "tip",
      link: "tools/",
      prefix: "tools/",
      collapsable: true,
      children: [{
        text: "linux",
        icon: "tip",
        link: "linux/",
        prefix: "linux/",
        children: ["01.安装linux系统的多种方式"],
      }, "github"]
      // children: "structure",
    },
    {
      text: "English",
      icon: "tip",
      link: "English/",
      prefix: "English/",
      collapsable: true,
      children: "structure",
    },
    {
      text: "二进制安全",
      icon: "tip",
      link: "pwn/",
      prefix: "pwn/",
      collapsable: true,
      children: "structure",
    },
    {
      text: "python",
      icon: "tip",
      link: "python/",
      prefix: "python/",
      collapsable: true,
      children: [{
        icon: "note",
        text: "python基础：",
        prefix: "python基础/",
        link: "python基础/",
        children: "structure",
      },
        {
          icon: "discover",
          text: "Django：",
          prefix: "Django/",
          link: "Django/",
          children: "structure",
        },
      ],

    },

    // "slides",
  ],
  // "/pwn/": "structure",
  // "/python/": "structure",
});
