<template><div><p><a name="93812c3d"></a></p>
<h2 id="_3-1-列表是什么" tabindex="-1"><a class="header-anchor" href="#_3-1-列表是什么" aria-hidden="true">#</a> 3.1 列表是什么</h2>
<p>列表由一系列按特定顺序排列的元素组成。<br />在Python中，用方括号（[]）来表示列表，并用逗号来分隔其中的元素。下面是一个简单的列表示例，这个列表包含几种自行车：</p>
<div class="language-python ext-py line-numbers-mode"><pre v-pre class="language-python"><code>bicycles <span class="token operator">=</span> <span class="token punctuation">[</span><span class="token string">'trek'</span><span class="token punctuation">,</span> <span class="token string">'cannondale'</span><span class="token punctuation">,</span> <span class="token string">'redline'</span><span class="token punctuation">,</span> <span class="token string">'specialized'</span><span class="token punctuation">]</span> 
<span class="token keyword">print</span><span class="token punctuation">(</span>bicycles<span class="token punctuation">)</span>
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div><div class="line-number"></div></div></div><p>如果你让Python将列表打印出来，Python将打印列表的内部表示，包括方括号：</p>
<div class="language-python ext-py line-numbers-mode"><pre v-pre class="language-python"><code><span class="token punctuation">[</span><span class="token string">'trek'</span><span class="token punctuation">,</span> <span class="token string">'cannondale'</span><span class="token punctuation">,</span> <span class="token string">'redline'</span><span class="token punctuation">,</span> <span class="token string">'specialized'</span><span class="token punctuation">]</span>
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div></div></div><p><a name="b2a27ec8"></a></p>
<h3 id="_3-1-1-访问列表元素" tabindex="-1"><a class="header-anchor" href="#_3-1-1-访问列表元素" aria-hidden="true">#</a> 3.1.1 访问列表元素</h3>
<p>列表是有序集合，因此要访问列表的任何元素，只需将该元素的位置或索引告诉Python即可。<br />要访问列表元素，可指出列表的名称，再指出元素的索引，并将其放在方括号内。</p>
<div class="language-python ext-py line-numbers-mode"><pre v-pre class="language-python"><code>bicycles <span class="token operator">=</span> <span class="token punctuation">[</span><span class="token string">'trek'</span><span class="token punctuation">,</span> <span class="token string">'cannondale'</span><span class="token punctuation">,</span> <span class="token string">'redline'</span><span class="token punctuation">,</span> <span class="token string">'specialized'</span><span class="token punctuation">]</span> 
<span class="token keyword">print</span><span class="token punctuation">(</span>bicycles<span class="token punctuation">[</span><span class="token number">0</span><span class="token punctuation">]</span><span class="token punctuation">)</span>
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div><div class="line-number"></div></div></div><p>当你请求获取列表元素时，Python只返回该元素，而不包<br />括方括号和引号：</p>
<div class="language-python ext-py line-numbers-mode"><pre v-pre class="language-python"><code>trek
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div></div></div><p>可使用方法title()让元素'trek'的格式更整洁</p>
<p><a name="77745a2d"></a></p>
<h3 id="_3-1-2-索引从0而不是1开始" tabindex="-1"><a class="header-anchor" href="#_3-1-2-索引从0而不是1开始" aria-hidden="true">#</a> 3.1.2 索引从0而不是1开始</h3>
<p>在Python中，第一个列表元素的索引为0，而不是1。<br />Python为访问最后一个列表元素提供了一种特殊语法。通过将索引指定为-1，可让Python返回最后一个列表元素。索引-2返回倒数第二个列表元素，索引-3返回倒数第三个列表元素，以此类推。</p>
<p><a name="302e1e8d"></a></p>
<h3 id="_3-1-3-使用列表中的各个值" tabindex="-1"><a class="header-anchor" href="#_3-1-3-使用列表中的各个值" aria-hidden="true">#</a> 3.1.3 使用列表中的各个值</h3>
<p>可像使用其他变量一样使用列表中的各个值。</p>
<p><a name="ded557da"></a></p>
<h2 id="_3-2-修改、添加和删除元素" tabindex="-1"><a class="header-anchor" href="#_3-2-修改、添加和删除元素" aria-hidden="true">#</a> 3.2 修改、添加和删除元素</h2>
<p><a name="d08101d0"></a></p>
<h3 id="_3-2-1-修改列表元素" tabindex="-1"><a class="header-anchor" href="#_3-2-1-修改列表元素" aria-hidden="true">#</a> 3.2.1 修改列表元素</h3>
<p>修改列表元素的语法与访问列表元素的语法类似。要修改列表元素，可指定列表名和要修改的元素的索引，再指定该元素的新值。</p>
<div class="language-python ext-py line-numbers-mode"><pre v-pre class="language-python"><code>motorcycles <span class="token operator">=</span> <span class="token punctuation">[</span><span class="token string">'honda'</span><span class="token punctuation">,</span> <span class="token string">'yamaha'</span><span class="token punctuation">,</span> <span class="token string">'suzuki'</span><span class="token punctuation">]</span> 
<span class="token keyword">print</span><span class="token punctuation">(</span>motorcycles<span class="token punctuation">)</span> 
motorcycles<span class="token punctuation">[</span><span class="token number">0</span><span class="token punctuation">]</span> <span class="token operator">=</span> <span class="token string">'ducati'</span> 
<span class="token keyword">print</span><span class="token punctuation">(</span>motorcycles<span class="token punctuation">)</span>
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><div class="language-python ext-py line-numbers-mode"><pre v-pre class="language-python"><code><span class="token punctuation">[</span><span class="token string">'honda'</span><span class="token punctuation">,</span> <span class="token string">'yamaha'</span><span class="token punctuation">,</span> <span class="token string">'suzuki'</span><span class="token punctuation">]</span> 
<span class="token punctuation">[</span><span class="token string">'ducati'</span><span class="token punctuation">,</span> <span class="token string">'yamaha'</span><span class="token punctuation">,</span> <span class="token string">'suzuki'</span><span class="token punctuation">]</span>
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div><div class="line-number"></div></div></div><p>你可以修改任何列表元素的值，而不仅仅是第一个元素的值。</p>
<p><a name="1c20b216"></a></p>
<h3 id="_3-2-2-在列表中添加元素" tabindex="-1"><a class="header-anchor" href="#_3-2-2-在列表中添加元素" aria-hidden="true">#</a> 3.2.2 在列表中添加元素</h3>
<p><a name="15c3505a"></a></p>
<h4 id="_1-在列表末尾添加元素" tabindex="-1"><a class="header-anchor" href="#_1-在列表末尾添加元素" aria-hidden="true">#</a> 1. 在列表末尾添加元素</h4>
<p>方法append()将元素'ducati'添加到了列表末尾，而不影响列表中的其他所有元素：</p>
<div class="language-python ext-py line-numbers-mode"><pre v-pre class="language-python"><code>motorcycles <span class="token operator">=</span> <span class="token punctuation">[</span><span class="token string">'honda'</span><span class="token punctuation">,</span> <span class="token string">'yamaha'</span><span class="token punctuation">,</span> <span class="token string">'suzuki'</span><span class="token punctuation">]</span> 
<span class="token keyword">print</span><span class="token punctuation">(</span>motorcycles<span class="token punctuation">)</span> 
motorcycles<span class="token punctuation">.</span>append<span class="token punctuation">(</span><span class="token string">'ducati'</span><span class="token punctuation">)</span> 
<span class="token keyword">print</span><span class="token punctuation">(</span>motorcycles<span class="token punctuation">)</span>
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><div class="language-python ext-py line-numbers-mode"><pre v-pre class="language-python"><code><span class="token punctuation">[</span><span class="token string">'honda'</span><span class="token punctuation">,</span> <span class="token string">'yamaha'</span><span class="token punctuation">,</span> <span class="token string">'suzuki'</span><span class="token punctuation">]</span> 
<span class="token punctuation">[</span><span class="token string">'honda'</span><span class="token punctuation">,</span> <span class="token string">'yamaha'</span><span class="token punctuation">,</span> <span class="token string">'suzuki'</span><span class="token punctuation">,</span> <span class="token string">'ducati'</span><span class="token punctuation">]</span>
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div><div class="line-number"></div></div></div><p>方法append()让动态地创建列表易如反掌，例如，你可以先创建一个空列表，再使用一系列的append()语句添加元素。</p>
<p><a name="1ae90806"></a></p>
<h4 id="_2-在列表中插入元素" tabindex="-1"><a class="header-anchor" href="#_2-在列表中插入元素" aria-hidden="true">#</a> 2. 在列表中插入元素</h4>
<p>使用方法insert()可在列表的任何位置添加新元素。</p>
<div class="language-python ext-py line-numbers-mode"><pre v-pre class="language-python"><code>motorcycles <span class="token operator">=</span> <span class="token punctuation">[</span><span class="token string">'honda'</span><span class="token punctuation">,</span> <span class="token string">'yamaha'</span><span class="token punctuation">,</span> <span class="token string">'suzuki'</span><span class="token punctuation">]</span> 
motorcycles<span class="token punctuation">.</span>insert<span class="token punctuation">(</span><span class="token number">0</span><span class="token punctuation">,</span> <span class="token string">'ducati'</span><span class="token punctuation">)</span> 
<span class="token keyword">print</span><span class="token punctuation">(</span>motorcycles<span class="token punctuation">)</span>
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><p>在这个示例中，值'ducati'被插入到了列表开头；方法insert()在索引0处添加空间，并将值'ducati'存储到这个地方。这种操作将列表中既有的每个元素都右移一个位置：</p>
<div class="language-python ext-py line-numbers-mode"><pre v-pre class="language-python"><code><span class="token punctuation">[</span><span class="token string">'ducati'</span><span class="token punctuation">,</span> <span class="token string">'honda'</span><span class="token punctuation">,</span> <span class="token string">'yamaha'</span><span class="token punctuation">,</span> <span class="token string">'suzuki'</span><span class="token punctuation">]</span>
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div></div></div><p><a name="835dbf3e"></a></p>
<h3 id="_3-2-3-从列表中删除元素" tabindex="-1"><a class="header-anchor" href="#_3-2-3-从列表中删除元素" aria-hidden="true">#</a> 3.2.3 从列表中删除元素</h3>
<p><a name="4a386608"></a></p>
<h4 id="_1-使用del语句删除元素" tabindex="-1"><a class="header-anchor" href="#_1-使用del语句删除元素" aria-hidden="true">#</a> 1. 使用del语句删除元素</h4>
<p>如果知道要删除的元素在列表中的位置，可使用del语句。</p>
<div class="language-python ext-py line-numbers-mode"><pre v-pre class="language-python"><code>motorcycles <span class="token operator">=</span> <span class="token punctuation">[</span><span class="token string">'honda'</span><span class="token punctuation">,</span> <span class="token string">'yamaha'</span><span class="token punctuation">,</span> <span class="token string">'suzuki'</span><span class="token punctuation">]</span> 
<span class="token keyword">print</span><span class="token punctuation">(</span>motorcycles<span class="token punctuation">)</span> 
<span class="token keyword">del</span> motorcycles<span class="token punctuation">[</span><span class="token number">0</span><span class="token punctuation">]</span> 
<span class="token keyword">print</span><span class="token punctuation">(</span>motorcycles<span class="token punctuation">)</span>
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><p>代码使用del删除了列表motorcycles中的第一个元素——'honda'：</p>
<div class="language-python ext-py line-numbers-mode"><pre v-pre class="language-python"><code><span class="token punctuation">[</span><span class="token string">'honda'</span><span class="token punctuation">,</span> <span class="token string">'yamaha'</span><span class="token punctuation">,</span> <span class="token string">'suzuki'</span><span class="token punctuation">]</span> 
<span class="token punctuation">[</span><span class="token string">'yamaha'</span><span class="token punctuation">,</span> <span class="token string">'suzuki'</span><span class="token punctuation">]</span>
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div><div class="line-number"></div></div></div><p>使用del可删除任何位置处的列表元素，条件是知道其索引。</p>
<p><a name="bb8b130a"></a></p>
<h4 id="_2-使用方法pop-删除元素" tabindex="-1"><a class="header-anchor" href="#_2-使用方法pop-删除元素" aria-hidden="true">#</a> 2. 使用方法pop（）删除元素</h4>
<p>方法pop()可删除列表末尾的元素，并让你能够接着使用它。术语弹出（pop）源自这样的类比：列表就像一个栈，而删除列表末尾的元素相当于弹出栈顶元素。</p>
<div class="language-python ext-py line-numbers-mode"><pre v-pre class="language-python"><code> motorcycles <span class="token operator">=</span> <span class="token punctuation">[</span><span class="token string">'honda'</span><span class="token punctuation">,</span> <span class="token string">'yamaha'</span><span class="token punctuation">,</span> <span class="token string">'suzuki'</span><span class="token punctuation">]</span> 
<span class="token keyword">print</span><span class="token punctuation">(</span>motorcycles<span class="token punctuation">)</span> 
popped_motorcycle <span class="token operator">=</span> motorcycles<span class="token punctuation">.</span>pop<span class="token punctuation">(</span><span class="token punctuation">)</span> 
<span class="token keyword">print</span><span class="token punctuation">(</span>motorcycles<span class="token punctuation">)</span> 
<span class="token keyword">print</span><span class="token punctuation">(</span>popped_motorcycle<span class="token punctuation">)</span>
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><div class="language-python ext-py line-numbers-mode"><pre v-pre class="language-python"><code><span class="token punctuation">[</span><span class="token string">'honda'</span><span class="token punctuation">,</span> <span class="token string">'yamaha'</span><span class="token punctuation">,</span> <span class="token string">'suzuki'</span><span class="token punctuation">]</span> 
<span class="token punctuation">[</span><span class="token string">'honda'</span><span class="token punctuation">,</span> <span class="token string">'yamaha'</span><span class="token punctuation">]</span> 
suzuki
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><p><a name="2881b6cb"></a></p>
<h4 id="_3-弹出列表中任何位置处的元素" tabindex="-1"><a class="header-anchor" href="#_3-弹出列表中任何位置处的元素" aria-hidden="true">#</a> 3. 弹出列表中任何位置处的元素</h4>
<p>实际上，你可以使用pop()来删除列表中任何位置的元素，只需在括号中指定要删除的元素的索引即可。</p>
<div class="language-python ext-py line-numbers-mode"><pre v-pre class="language-python"><code>motorcycles <span class="token operator">=</span> <span class="token punctuation">[</span><span class="token string">'honda'</span><span class="token punctuation">,</span> <span class="token string">'yamaha'</span><span class="token punctuation">,</span> <span class="token string">'suzuki'</span><span class="token punctuation">]</span> 
first_owned <span class="token operator">=</span> motorcycles<span class="token punctuation">.</span>pop<span class="token punctuation">(</span><span class="token number">0</span><span class="token punctuation">)</span> 
<span class="token keyword">print</span><span class="token punctuation">(</span><span class="token string">'The first motorcycle I owned was a '</span> <span class="token operator">+</span> first_owned<span class="token punctuation">.</span>title<span class="token punctuation">(</span><span class="token punctuation">)</span> <span class="token operator">+</span> <span class="token string">'.'</span><span class="token punctuation">)</span>
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><div class="language-python ext-py line-numbers-mode"><pre v-pre class="language-python"><code>The first motorcycle I owned was a Honda<span class="token punctuation">.</span>
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div></div></div><p>别忘了，每当你使用pop()时，被弹出的元素就不再在列表中了。</p>
<p><a name="421b32a3"></a></p>
<h4 id="_4-根据值删除元素" tabindex="-1"><a class="header-anchor" href="#_4-根据值删除元素" aria-hidden="true">#</a> 4. 根据值删除元素</h4>
<p>不知道要从列表中删除的值所处的位置，只知道要删除的元素的值，可使用方法remove()。</p>
<div class="language-python ext-py line-numbers-mode"><pre v-pre class="language-python"><code>motorcycles <span class="token operator">=</span> <span class="token punctuation">[</span><span class="token string">'honda'</span><span class="token punctuation">,</span> <span class="token string">'yamaha'</span><span class="token punctuation">,</span> <span class="token string">'suzuki'</span><span class="token punctuation">,</span> <span class="token string">'ducati'</span><span class="token punctuation">]</span> 
<span class="token keyword">print</span><span class="token punctuation">(</span>motorcycles<span class="token punctuation">)</span> 
motorcycles<span class="token punctuation">.</span>remove<span class="token punctuation">(</span><span class="token string">'ducati'</span><span class="token punctuation">)</span> 
<span class="token keyword">print</span><span class="token punctuation">(</span>motorcycles<span class="token punctuation">)</span>
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><div class="language-python ext-py line-numbers-mode"><pre v-pre class="language-python"><code><span class="token punctuation">[</span><span class="token string">'honda'</span><span class="token punctuation">,</span> <span class="token string">'yamaha'</span><span class="token punctuation">,</span> <span class="token string">'suzuki'</span><span class="token punctuation">,</span> <span class="token string">'ducati'</span><span class="token punctuation">]</span> 
<span class="token punctuation">[</span><span class="token string">'honda'</span><span class="token punctuation">,</span> <span class="token string">'yamaha'</span><span class="token punctuation">,</span> <span class="token string">'suzuki'</span><span class="token punctuation">]</span>
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div><div class="line-number"></div></div></div><p><a name="e2d201c2"></a></p>
<h2 id="_3-3-组织列表" tabindex="-1"><a class="header-anchor" href="#_3-3-组织列表" aria-hidden="true">#</a> 3.3 组织列表</h2>
<p><a name="78e83c5e"></a></p>
<h3 id="_3-3-1-使用方法sort-对列表进行永久性排序" tabindex="-1"><a class="header-anchor" href="#_3-3-1-使用方法sort-对列表进行永久性排序" aria-hidden="true">#</a> 3.3.1 使用方法sort（）对列表进行永久性排序</h3>
<p>Python方法sort()让你能够较为轻松地对列表进行排序。</p>
<div class="language-python ext-py line-numbers-mode"><pre v-pre class="language-python"><code>cars <span class="token operator">=</span> <span class="token punctuation">[</span><span class="token string">'bmw'</span><span class="token punctuation">,</span> <span class="token string">'audi'</span><span class="token punctuation">,</span> <span class="token string">'toyota'</span><span class="token punctuation">,</span> <span class="token string">'subaru'</span><span class="token punctuation">]</span> 
cars<span class="token punctuation">.</span>sort<span class="token punctuation">(</span><span class="token punctuation">)</span>
<span class="token keyword">print</span><span class="token punctuation">(</span>cars<span class="token punctuation">)</span>
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><div class="language-python ext-py line-numbers-mode"><pre v-pre class="language-python"><code><span class="token punctuation">[</span><span class="token string">'audi'</span><span class="token punctuation">,</span> <span class="token string">'bmw'</span><span class="token punctuation">,</span> <span class="token string">'subaru'</span><span class="token punctuation">,</span> <span class="token string">'toyota'</span><span class="token punctuation">]</span>
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div></div></div><p>你还可以按与字母顺序相反的顺序排列列表元素，为此，只需向sort()方法传递参数reverse=True。</p>
<div class="language-python ext-py line-numbers-mode"><pre v-pre class="language-python"><code>cars <span class="token operator">=</span> <span class="token punctuation">[</span><span class="token string">'bmw'</span><span class="token punctuation">,</span> <span class="token string">'audi'</span><span class="token punctuation">,</span> <span class="token string">'toyota'</span><span class="token punctuation">,</span> <span class="token string">'subaru'</span><span class="token punctuation">]</span>
cars<span class="token punctuation">.</span>sort<span class="token punctuation">(</span>reverse<span class="token operator">=</span><span class="token boolean">True</span><span class="token punctuation">)</span> 
<span class="token keyword">print</span><span class="token punctuation">(</span>cars<span class="token punctuation">)</span>
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><div class="language-python ext-py line-numbers-mode"><pre v-pre class="language-python"><code><span class="token punctuation">[</span><span class="token string">'toyota'</span><span class="token punctuation">,</span> <span class="token string">'subaru'</span><span class="token punctuation">,</span> <span class="token string">'bmw'</span><span class="token punctuation">,</span> <span class="token string">'audi'</span><span class="token punctuation">]</span>
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div></div></div><p><a name="a8d24903"></a></p>
<h3 id="_3-3-2-使用函数sorted-对列表进行临时排序" tabindex="-1"><a class="header-anchor" href="#_3-3-2-使用函数sorted-对列表进行临时排序" aria-hidden="true">#</a> 3.3.2 使用函数sorted（）对列表进行临时排序</h3>
<p>要保留列表元素原来的排列顺序，同时以特定的顺序呈现它们，可使用函数sorted()。函数sorted()让你能够按特定顺序显示列表元素，同时不影响它们在列表中的原始排列顺序。</p>
<div class="language-python ext-py line-numbers-mode"><pre v-pre class="language-python"><code>cars <span class="token operator">=</span> <span class="token punctuation">[</span><span class="token string">'bmw'</span><span class="token punctuation">,</span> <span class="token string">'audi'</span><span class="token punctuation">,</span> <span class="token string">'toyota'</span><span class="token punctuation">,</span> <span class="token string">'subaru'</span><span class="token punctuation">]</span> 
<span class="token keyword">print</span><span class="token punctuation">(</span><span class="token string">"Here is the original list:"</span><span class="token punctuation">)</span> 
<span class="token keyword">print</span><span class="token punctuation">(</span>cars<span class="token punctuation">)</span> 
<span class="token keyword">print</span><span class="token punctuation">(</span><span class="token string">"\nHere is the sorted list:"</span><span class="token punctuation">)</span> 
<span class="token keyword">print</span><span class="token punctuation">(</span><span class="token builtin">sorted</span><span class="token punctuation">(</span>cars<span class="token punctuation">)</span><span class="token punctuation">)</span> 
<span class="token keyword">print</span><span class="token punctuation">(</span><span class="token string">"\nHere is the original list again:"</span><span class="token punctuation">)</span> 
<span class="token keyword">print</span><span class="token punctuation">(</span>cars<span class="token punctuation">)</span>
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><div class="language-python ext-py line-numbers-mode"><pre v-pre class="language-python"><code>Here <span class="token keyword">is</span> the original <span class="token builtin">list</span><span class="token punctuation">:</span> 
<span class="token punctuation">[</span><span class="token string">'bmw'</span><span class="token punctuation">,</span> <span class="token string">'audi'</span><span class="token punctuation">,</span> <span class="token string">'toyota'</span><span class="token punctuation">,</span> <span class="token string">'subaru'</span><span class="token punctuation">]</span> 
Here <span class="token keyword">is</span> the <span class="token builtin">sorted</span> <span class="token builtin">list</span><span class="token punctuation">:</span> 
<span class="token punctuation">[</span><span class="token string">'audi'</span><span class="token punctuation">,</span> <span class="token string">'bmw'</span><span class="token punctuation">,</span> <span class="token string">'subaru'</span><span class="token punctuation">,</span> <span class="token string">'toyota'</span><span class="token punctuation">]</span> 
Here <span class="token keyword">is</span> the original <span class="token builtin">list</span> again<span class="token punctuation">:</span> 
<span class="token punctuation">[</span><span class="token string">'bmw'</span><span class="token punctuation">,</span> <span class="token string">'audi'</span><span class="token punctuation">,</span> <span class="token string">'toyota'</span><span class="token punctuation">,</span> <span class="token string">'subaru'</span><span class="token punctuation">]</span>
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><p>如果你要按与字母顺序相反的顺序显示列表，也可向函数sorted()传递参数reverse=True。</p>
<p><a name="754b04f4"></a></p>
<h3 id="_3-3-3-倒着打印列表" tabindex="-1"><a class="header-anchor" href="#_3-3-3-倒着打印列表" aria-hidden="true">#</a> 3.3.3 倒着打印列表</h3>
<p>要反转列表元素的排列顺序，可使用方法reverse()。</p>
<div class="language-python ext-py line-numbers-mode"><pre v-pre class="language-python"><code>cars <span class="token operator">=</span> <span class="token punctuation">[</span><span class="token string">'bmw'</span><span class="token punctuation">,</span> <span class="token string">'audi'</span><span class="token punctuation">,</span> <span class="token string">'toyota'</span><span class="token punctuation">,</span> <span class="token string">'subaru'</span><span class="token punctuation">]</span> 
<span class="token keyword">print</span><span class="token punctuation">(</span>cars<span class="token punctuation">)</span> 
cars<span class="token punctuation">.</span>reverse<span class="token punctuation">(</span><span class="token punctuation">)</span> 
<span class="token keyword">print</span><span class="token punctuation">(</span>cars<span class="token punctuation">)</span>
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><div class="language-python ext-py line-numbers-mode"><pre v-pre class="language-python"><code><span class="token punctuation">[</span><span class="token string">'bmw'</span><span class="token punctuation">,</span> <span class="token string">'audi'</span><span class="token punctuation">,</span> <span class="token string">'toyota'</span><span class="token punctuation">,</span> <span class="token string">'subaru'</span><span class="token punctuation">]</span> 
<span class="token punctuation">[</span><span class="token string">'subaru'</span><span class="token punctuation">,</span> <span class="token string">'toyota'</span><span class="token punctuation">,</span> <span class="token string">'audi'</span><span class="token punctuation">,</span> <span class="token string">'bmw'</span><span class="token punctuation">]</span>
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div><div class="line-number"></div></div></div><p>注意，reverse()不是指按与字母顺序相反的顺序排列列表元素，而只是反转列表元素的排列顺序<br />方法reverse()永久性地修改列表元素的排列顺序，但可随时恢复到原来的排列顺序，为此只需对列表再次调用reverse()即可。</p>
<p><a name="709781b3"></a></p>
<h3 id="_3-3-4-确定列表的长度" tabindex="-1"><a class="header-anchor" href="#_3-3-4-确定列表的长度" aria-hidden="true">#</a> 3.3.4 确定列表的长度</h3>
<p>使用函数len()可快速获悉列表的长度。</p>
<div class="language-python ext-py line-numbers-mode"><pre v-pre class="language-python"><code><span class="token operator">>></span><span class="token operator">></span> cars <span class="token operator">=</span> <span class="token punctuation">[</span><span class="token string">'bmw'</span><span class="token punctuation">,</span> <span class="token string">'audi'</span><span class="token punctuation">,</span> <span class="token string">'toyota'</span><span class="token punctuation">,</span> <span class="token string">'subaru'</span><span class="token punctuation">]</span>
<span class="token operator">>></span><span class="token operator">></span> <span class="token builtin">len</span><span class="token punctuation">(</span>cars<span class="token punctuation">)</span>
<span class="token number">4</span>
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><p><a name="9c2abdc2"></a></p>
<h2 id="_3-4-使用列表时避免索引错误" tabindex="-1"><a class="header-anchor" href="#_3-4-使用列表时避免索引错误" aria-hidden="true">#</a> 3.4 使用列表时避免索引错误</h2>
<p><a name="6b42bce3"></a></p>
<h2 id="_3-5-小结" tabindex="-1"><a class="header-anchor" href="#_3-5-小结" aria-hidden="true">#</a> 3.5 小结</h2>
<p>在本章中，你学习了：列表是什么以及如何使用其中的元素；如何定义列表以及如何增删元素；如何对列表进行永久性排序，以及如何为展示列表而进行临时排序；如何确定列表的长度，以及在使用列表时如何避免索引错误。<br />在第4章，你将学习如何以更高效的方式处理列表元素。通过使用为数不多的几行代码来遍历列表元素，你就能高效地处理它们，即便列表包含数千乃至数百万个元素。</p>
<p><a name="14581c38"></a></p>
<h1 id="" tabindex="-1"><a class="header-anchor" href="#" aria-hidden="true">#</a> </h1>
</div></template>


