<template><div><h1 id="_06-第六章-字典" tabindex="-1"><a class="header-anchor" href="#_06-第六章-字典" aria-hidden="true">#</a> 06.第六章 字典</h1>
<p><a name="e36d6359"></a></p>
<h2 id="_6-1-一个简单的字典" tabindex="-1"><a class="header-anchor" href="#_6-1-一个简单的字典" aria-hidden="true">#</a> 6.1 一个简单的字典</h2>
<p>来看一个游戏，其中包含一些外星人，这些外星人的颜色和点数各不相同。下面是一个简单的字典，存储了有关特定外星人的信息：</p>
<div class="language-python ext-py line-numbers-mode"><pre v-pre class="language-python"><code>alien_0 <span class="token operator">=</span> <span class="token punctuation">{</span><span class="token string">'color'</span><span class="token punctuation">:</span> <span class="token string">'green'</span><span class="token punctuation">,</span> <span class="token string">'points'</span><span class="token punctuation">:</span> <span class="token number">5</span><span class="token punctuation">}</span> 
<span class="token keyword">print</span><span class="token punctuation">(</span>alien_0<span class="token punctuation">[</span><span class="token string">'color'</span><span class="token punctuation">]</span><span class="token punctuation">)</span> 
<span class="token keyword">print</span><span class="token punctuation">(</span>alien_0<span class="token punctuation">[</span><span class="token string">'points'</span><span class="token punctuation">]</span><span class="token punctuation">)</span>
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><p>字典alien_0存储了外星人的颜色和点数。使用两条print语句来访问并打印这些信息，如下所示：</p>
<div class="language-python ext-py line-numbers-mode"><pre v-pre class="language-python"><code>green 
<span class="token number">5</span>
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div><div class="line-number"></div></div></div><p><a name="828e26a1"></a></p>
<h2 id="_6-2-使用字典" tabindex="-1"><a class="header-anchor" href="#_6-2-使用字典" aria-hidden="true">#</a> 6.2 使用字典</h2>
<p>在Python中，字典是一系列键—值对。每个键都与一个值相关联，你可以使用键来访问与之相关联的值。与键相关联的值可以是数字、字符串、列表乃至字典。事实上，可将任何Python对象用作字典中的值。<br />在Python中，字典用放在花括号{}中的一系列键—值对表示，如前面的示例所示：</p>
<div class="language-python ext-py line-numbers-mode"><pre v-pre class="language-python"><code>alien_0 <span class="token operator">=</span> <span class="token punctuation">{</span><span class="token string">'color'</span><span class="token punctuation">:</span> <span class="token string">'green'</span><span class="token punctuation">,</span> <span class="token string">'points'</span><span class="token punctuation">:</span> <span class="token number">5</span><span class="token punctuation">}</span>
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div></div></div><p>键—值对是两个相关联的值。指定键时，Python将返回与之相关联的值。键和值之间用冒号分隔，而键—值对之间用逗号分隔。在字典中，你想存储多少个键—值对都可以。<br />最简单的字典只有一个键—值对，如下述修改后的字典alien_0所示：</p>
<div class="language-python ext-py line-numbers-mode"><pre v-pre class="language-python"><code>alien_0 <span class="token operator">=</span> <span class="token punctuation">{</span><span class="token string">'color'</span><span class="token punctuation">:</span> <span class="token string">'green'</span><span class="token punctuation">}</span>
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div></div></div><p>这个字典只存储了一项有关alien_0的信息，具体地说是这个外星人的颜色。在这个字典中，字符串'color'是一个键，与之相关联的值为'green'。</p>
<p><a name="43f026d3"></a></p>
<h3 id="_6-2-1-访问字典中的值" tabindex="-1"><a class="header-anchor" href="#_6-2-1-访问字典中的值" aria-hidden="true">#</a> 6.2.1 访问字典中的值</h3>
<p>要获取与键相关联的值，可依次指定字典名和放在方括号内的键，如下所示：</p>
<div class="language-python ext-py line-numbers-mode"><pre v-pre class="language-python"><code>alien_0 <span class="token operator">=</span> <span class="token punctuation">{</span><span class="token string">'color'</span><span class="token punctuation">:</span> <span class="token string">'green'</span><span class="token punctuation">}</span> 
<span class="token keyword">print</span><span class="token punctuation">(</span>alien_0<span class="token punctuation">[</span><span class="token string">'color'</span><span class="token punctuation">]</span><span class="token punctuation">)</span>
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div><div class="line-number"></div></div></div><p>这将返回字典alien_0中与键'color'相关联的值：</p>
<div class="language-python ext-py line-numbers-mode"><pre v-pre class="language-python"><code>green
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div></div></div><p>字典中可包含任意数量的键—值对。<br />现在，你可以访问外星人alien_0的颜色和点数。如果玩家射杀了这个外星人，你就可以使用下面的代码来确定玩家应获得多少个点：</p>
<div class="language-python ext-py line-numbers-mode"><pre v-pre class="language-python"><code>alien_0 <span class="token operator">=</span> <span class="token punctuation">{</span><span class="token string">'color'</span><span class="token punctuation">:</span> <span class="token string">'green'</span><span class="token punctuation">,</span> <span class="token string">'points'</span><span class="token punctuation">:</span> <span class="token number">5</span><span class="token punctuation">}</span> 
new_points <span class="token operator">=</span> alien_0<span class="token punctuation">[</span><span class="token string">'points'</span><span class="token punctuation">]</span> 
<span class="token keyword">print</span><span class="token punctuation">(</span><span class="token string">"You just earned "</span> <span class="token operator">+</span> <span class="token builtin">str</span><span class="token punctuation">(</span>new_points<span class="token punctuation">)</span> <span class="token operator">+</span> <span class="token string">" points!"</span><span class="token punctuation">)</span>
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><p>上述代码首先定义了一个字典，然后从这个字典中获取与键'points'相关联的值，并将这个值存储在变量new_points中。接下来，将这个整数转换为字符串，并打印一条消息，指出玩家获得了多少个点：</p>
<div class="language-python ext-py line-numbers-mode"><pre v-pre class="language-python"><code>You just earned <span class="token number">5</span> points!
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div></div></div><p><a name="90b8154a"></a></p>
<h3 id="_6-2-2-添加键-值对" tabindex="-1"><a class="header-anchor" href="#_6-2-2-添加键-值对" aria-hidden="true">#</a> 6.2.2 添加键-值对</h3>
<p>字典是一种动态结构，可随时在其中添加键—值对。要添加键—值对，可依次指定字典名、用方括号括起的键和相关联的值。</p>
<div class="language-python ext-py line-numbers-mode"><pre v-pre class="language-python"><code>alien_0 <span class="token operator">=</span> <span class="token punctuation">{</span><span class="token string">'color'</span><span class="token punctuation">:</span> <span class="token string">'green'</span><span class="token punctuation">,</span> <span class="token string">'points'</span><span class="token punctuation">:</span> <span class="token number">5</span><span class="token punctuation">}</span> 
<span class="token keyword">print</span><span class="token punctuation">(</span>alien_0<span class="token punctuation">)</span> 
alien_0<span class="token punctuation">[</span><span class="token string">'x_position'</span><span class="token punctuation">]</span> <span class="token operator">=</span> <span class="token number">0</span> 
alien_0<span class="token punctuation">[</span><span class="token string">'y_position'</span><span class="token punctuation">]</span> <span class="token operator">=</span> <span class="token number">25</span> 
<span class="token keyword">print</span><span class="token punctuation">(</span>alien_0<span class="token punctuation">)</span>
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><div class="language-python ext-py line-numbers-mode"><pre v-pre class="language-python"><code><span class="token punctuation">{</span><span class="token string">'color'</span><span class="token punctuation">:</span> <span class="token string">'green'</span><span class="token punctuation">,</span> <span class="token string">'points'</span><span class="token punctuation">:</span> <span class="token number">5</span><span class="token punctuation">}</span> 
<span class="token punctuation">{</span><span class="token string">'color'</span><span class="token punctuation">:</span> <span class="token string">'green'</span><span class="token punctuation">,</span> <span class="token string">'points'</span><span class="token punctuation">:</span> <span class="token number">5</span><span class="token punctuation">,</span> <span class="token string">'y_position'</span><span class="token punctuation">:</span> <span class="token number">25</span><span class="token punctuation">,</span> <span class="token string">'x_position'</span><span class="token punctuation">:</span> <span class="token number">0</span><span class="token punctuation">}</span>
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div><div class="line-number"></div></div></div><p><a name="34e6857f"></a></p>
<h3 id="_6-2-3-先创建一个空字典" tabindex="-1"><a class="header-anchor" href="#_6-2-3-先创建一个空字典" aria-hidden="true">#</a> 6.2.3 先创建一个空字典</h3>
<p>有时候，在空字典中添加键—值对是为了方便，而有时候必须这样做。为此，可先使用一对空的花括号定义一个字典，再分行添加各个键—值对。</p>
<div class="language-python ext-py line-numbers-mode"><pre v-pre class="language-python"><code>alien_0 <span class="token operator">=</span> <span class="token punctuation">{</span><span class="token punctuation">}</span> 
alien_0<span class="token punctuation">[</span><span class="token string">'color'</span><span class="token punctuation">]</span> <span class="token operator">=</span> <span class="token string">'green'</span> 
alien_0<span class="token punctuation">[</span><span class="token string">'points'</span><span class="token punctuation">]</span> <span class="token operator">=</span> <span class="token number">5</span>
<span class="token keyword">print</span><span class="token punctuation">(</span>alien_0<span class="token punctuation">)</span>
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><p>这里首先定义了空字典alien_0，再在其中添加颜色和点数，得到前述示例一直在使用的字典：</p>
<div class="language-python ext-py line-numbers-mode"><pre v-pre class="language-python"><code><span class="token punctuation">{</span><span class="token string">'color'</span><span class="token punctuation">:</span> <span class="token string">'green'</span><span class="token punctuation">,</span> <span class="token string">'points'</span><span class="token punctuation">:</span> <span class="token number">5</span><span class="token punctuation">}</span>
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div></div></div><p>使用字典来存储用户提供的数据或在编写能自动生成大量键—值对的代码时，通常都需要先定义一个空字典。</p>
<p><a name="34d988a1"></a></p>
<h3 id="_6-2-4-修改字典中的值" tabindex="-1"><a class="header-anchor" href="#_6-2-4-修改字典中的值" aria-hidden="true">#</a> 6.2.4 修改字典中的值</h3>
<p>要修改字典中的值，可依次指定字典名、用方括号括起的键以及与该键相关联的新值。</p>
<div class="language-python ext-py line-numbers-mode"><pre v-pre class="language-python"><code>alien_0 <span class="token operator">=</span> <span class="token punctuation">{</span><span class="token string">'color'</span><span class="token punctuation">:</span> <span class="token string">'green'</span><span class="token punctuation">}</span> 
<span class="token keyword">print</span><span class="token punctuation">(</span><span class="token string">"The alien is "</span> <span class="token operator">+</span> alien_0<span class="token punctuation">[</span><span class="token string">'color'</span><span class="token punctuation">]</span> <span class="token operator">+</span> <span class="token string">"."</span><span class="token punctuation">)</span> 
alien_0<span class="token punctuation">[</span><span class="token string">'color'</span><span class="token punctuation">]</span> <span class="token operator">=</span> <span class="token string">'yellow'</span> 
<span class="token keyword">print</span><span class="token punctuation">(</span><span class="token string">"The alien is now "</span> <span class="token operator">+</span> alien_0<span class="token punctuation">[</span><span class="token string">'color'</span><span class="token punctuation">]</span> <span class="token operator">+</span> <span class="token string">"."</span><span class="token punctuation">)</span>
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><div class="language-python ext-py line-numbers-mode"><pre v-pre class="language-python"><code>The alien <span class="token keyword">is</span> green<span class="token punctuation">.</span> 
The alien <span class="token keyword">is</span> now yellow<span class="token punctuation">.</span>
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div><div class="line-number"></div></div></div><p>来看一个更有趣的例子：对一个能够以不同速度移动的外星人的位置进行跟踪。为此，我们将存储该外星人的当前速度，并据此确定该外星人将向右移动多远：</p>
<div class="language-python ext-py line-numbers-mode"><pre v-pre class="language-python"><code>alien_0 <span class="token operator">=</span> <span class="token punctuation">{</span><span class="token string">'x_position'</span><span class="token punctuation">:</span> <span class="token number">0</span><span class="token punctuation">,</span> <span class="token string">'y_position'</span><span class="token punctuation">:</span> <span class="token number">25</span><span class="token punctuation">,</span> <span class="token string">'speed'</span><span class="token punctuation">:</span> <span class="token string">'medium'</span><span class="token punctuation">}</span> 
<span class="token keyword">print</span><span class="token punctuation">(</span><span class="token string">"Original x-position: "</span> <span class="token operator">+</span> <span class="token builtin">str</span><span class="token punctuation">(</span>alien_0<span class="token punctuation">[</span><span class="token string">'x_position'</span><span class="token punctuation">]</span><span class="token punctuation">)</span><span class="token punctuation">)</span> 
<span class="token comment"># 向右移动外星人</span>
<span class="token comment"># 据外星人当前速度决定将其移动多远</span>
 <span class="token keyword">if</span> alien_0<span class="token punctuation">[</span><span class="token string">'speed'</span><span class="token punctuation">]</span> <span class="token operator">==</span> <span class="token string">'slow'</span><span class="token punctuation">:</span> 
    x_increment <span class="token operator">=</span> <span class="token number">1</span> 
<span class="token keyword">elif</span> alien_0<span class="token punctuation">[</span><span class="token string">'speed'</span><span class="token punctuation">]</span> <span class="token operator">==</span> <span class="token string">'medium'</span><span class="token punctuation">:</span> 
    x_increment <span class="token operator">=</span> <span class="token number">2</span> 
<span class="token keyword">else</span><span class="token punctuation">:</span> 
 <span class="token comment"># 这个外星人的速度一定很快</span>
   x_increment <span class="token operator">=</span> <span class="token number">3</span> 
<span class="token comment"># 新位置等于老位置加上增量</span>
alien_0<span class="token punctuation">[</span><span class="token string">'x_position'</span><span class="token punctuation">]</span> <span class="token operator">=</span> alien_0<span class="token punctuation">[</span><span class="token string">'x_position'</span><span class="token punctuation">]</span> <span class="token operator">+</span> x_increment
<span class="token keyword">print</span><span class="token punctuation">(</span><span class="token string">"New x-position: "</span> <span class="token operator">+</span> <span class="token builtin">str</span><span class="token punctuation">(</span>alien_0<span class="token punctuation">[</span><span class="token string">'x_position'</span><span class="token punctuation">]</span><span class="token punctuation">)</span><span class="token punctuation">)</span>
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><p>我们首先定义了一个外星人，其中包含初始的x坐标和y坐标，还有速度'medium'。使用了一个if-elif-else结构来确定外星人应向右移动多远，并将这个值存储在变量x_increment中。如果外星人的速度为'slow'，它将向右移动一个单位；如果速度为'medium'，将向右移动两个单位；如果为'fast'，将向右移动三个单位。确定移动量后，将其与x_position的当前值相加，再将结果关联到字典中的键x_position。</p>
<div class="language-python ext-py line-numbers-mode"><pre v-pre class="language-python"><code>Original x<span class="token operator">-</span>position<span class="token punctuation">:</span> <span class="token number">0</span> 
New x<span class="token operator">-</span>position<span class="token punctuation">:</span> <span class="token number">2</span>
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div><div class="line-number"></div></div></div><p>要将这个速度中等的外星人变成速度很快的外星人，可添加如下代码行：</p>
<div class="language-python ext-py line-numbers-mode"><pre v-pre class="language-python"><code>alien_0<span class="token punctuation">[</span><span class="token string">'speed'</span><span class="token punctuation">]</span> <span class="token operator">=</span> fast
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div></div></div><p>再次运行这些代码时，其中的if-elif-else结构将把一个更大的值赋给变量x_increment。</p>
<p><a name="0e1067ac"></a></p>
<h3 id="_6-2-5-删除键-值对" tabindex="-1"><a class="header-anchor" href="#_6-2-5-删除键-值对" aria-hidden="true">#</a> 6.2.5 删除键-值对</h3>
<p>对于字典中不再需要的信息，可使用del语句将相应的键—值对彻底删除。使用del语句时，必须指定字典名和要删除的键。</p>
<div class="language-python ext-py line-numbers-mode"><pre v-pre class="language-python"><code>alien_0 <span class="token operator">=</span> <span class="token punctuation">{</span><span class="token string">'color'</span><span class="token punctuation">:</span> <span class="token string">'green'</span><span class="token punctuation">,</span> <span class="token string">'points'</span><span class="token punctuation">:</span> <span class="token number">5</span><span class="token punctuation">}</span> 
<span class="token keyword">print</span><span class="token punctuation">(</span>alien_0<span class="token punctuation">)</span> 
<span class="token keyword">del</span> alien_0<span class="token punctuation">[</span><span class="token string">'points'</span><span class="token punctuation">]</span> 
<span class="token keyword">print</span><span class="token punctuation">(</span>alien_0<span class="token punctuation">)</span>
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><div class="language-python ext-py line-numbers-mode"><pre v-pre class="language-python"><code><span class="token punctuation">{</span><span class="token string">'color'</span><span class="token punctuation">:</span> <span class="token string">'green'</span><span class="token punctuation">,</span> <span class="token string">'points'</span><span class="token punctuation">:</span> <span class="token number">5</span><span class="token punctuation">}</span> 
<span class="token punctuation">{</span><span class="token string">'color'</span><span class="token punctuation">:</span> <span class="token string">'green'</span><span class="token punctuation">}</span>
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div><div class="line-number"></div></div></div><p>注意： 删除的键—值对永远消失了。</p>
<p><a name="fb39ede2"></a></p>
<h3 id="_6-2-6-由类似对象组成的字典" tabindex="-1"><a class="header-anchor" href="#_6-2-6-由类似对象组成的字典" aria-hidden="true">#</a> 6.2.6 由类似对象组成的字典</h3>
<p>在前面的示例中，字典存储的是一个对象（游戏中的一个外星人）的多种信息，但你也可以使用字典来存储众多对象的同一种信息。</p>
<div class="language-python ext-py line-numbers-mode"><pre v-pre class="language-python"><code>favorite_languages <span class="token operator">=</span> <span class="token punctuation">{</span> 
 <span class="token string">'jen'</span><span class="token punctuation">:</span> <span class="token string">'python'</span><span class="token punctuation">,</span> 
 <span class="token string">'sarah'</span><span class="token punctuation">:</span> <span class="token string">'c'</span><span class="token punctuation">,</span> 
 <span class="token string">'edward'</span><span class="token punctuation">:</span> <span class="token string">'ruby'</span><span class="token punctuation">,</span> 
 <span class="token string">'phil'</span><span class="token punctuation">:</span> <span class="token string">'python'</span><span class="token punctuation">,</span> 
 <span class="token punctuation">}</span>
  <span class="token keyword">print</span><span class="token punctuation">(</span><span class="token string">"Sarah's favorite language is "</span> <span class="token operator">+</span> 
 favorite_languages<span class="token punctuation">[</span><span class="token string">'sarah'</span><span class="token punctuation">]</span><span class="token punctuation">.</span>title<span class="token punctuation">(</span><span class="token punctuation">)</span> <span class="token operator">+</span> <span class="token string">"."</span><span class="token punctuation">)</span>
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><div class="language-python ext-py line-numbers-mode"><pre v-pre class="language-python"><code>Sarah's favorite language <span class="token keyword">is</span> C<span class="token punctuation">.</span>
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div></div></div><p><a name="43fd035b"></a></p>
<h2 id="_6-3-遍历字典" tabindex="-1"><a class="header-anchor" href="#_6-3-遍历字典" aria-hidden="true">#</a> 6.3 遍历字典</h2>
<p><a name="8f5718d9"></a></p>
<h3 id="_6-3-1-遍历所有的键-值对" tabindex="-1"><a class="header-anchor" href="#_6-3-1-遍历所有的键-值对" aria-hidden="true">#</a> 6.3.1 遍历所有的键-值对</h3>
<p>下面的字典存储一名用户的用户名、名和姓，可以使用一个for循环来遍历这个字典：：</p>
<div class="language-python ext-py line-numbers-mode"><pre v-pre class="language-python"><code>user_0 <span class="token operator">=</span> <span class="token punctuation">{</span> 
 <span class="token string">'username'</span><span class="token punctuation">:</span> <span class="token string">'efermi'</span><span class="token punctuation">,</span> 
 <span class="token string">'first'</span><span class="token punctuation">:</span> <span class="token string">'enrico'</span><span class="token punctuation">,</span> 
 <span class="token string">'last'</span><span class="token punctuation">:</span> <span class="token string">'fermi'</span><span class="token punctuation">,</span> 
 <span class="token punctuation">}</span>
 <span class="token keyword">for</span> key<span class="token punctuation">,</span> value <span class="token keyword">in</span> user_0<span class="token punctuation">.</span>items<span class="token punctuation">(</span><span class="token punctuation">)</span><span class="token punctuation">:</span> 
   <span class="token keyword">print</span><span class="token punctuation">(</span><span class="token string">"\nKey: "</span> <span class="token operator">+</span> key<span class="token punctuation">)</span> 
   <span class="token keyword">print</span><span class="token punctuation">(</span><span class="token string">"Value: "</span> <span class="token operator">+</span> value<span class="token punctuation">)</span>
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><p>要编写用于遍历字典的for循环，可声明两个变量，用于存储键—值对中的键和值。对于这两个变量，可使用任何名称。下面的代码使用了简单的变量名，这完全可行：</p>
<div class="language-python ext-py line-numbers-mode"><pre v-pre class="language-python"><code><span class="token keyword">for</span> k<span class="token punctuation">,</span> v <span class="token keyword">in</span> user_0<span class="token punctuation">.</span>items<span class="token punctuation">(</span><span class="token punctuation">)</span>
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div></div></div><p>for语句的第二部分包含字典名和方法items()，它返回一个键—值对列表。</p>
<div class="language-python ext-py line-numbers-mode"><pre v-pre class="language-python"><code>Key<span class="token punctuation">:</span> last 
Value<span class="token punctuation">:</span> fermi 
Key<span class="token punctuation">:</span> first 
Value<span class="token punctuation">:</span> enrico 
Key<span class="token punctuation">:</span> username 
Value<span class="token punctuation">:</span> efermi
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><p>注意，即便遍历字典时，键—值对的返回顺序也与存储顺序不同。Python不关心键—值对的存储顺序，而只跟踪键和值之间的关联关系。</p>
<div class="language-python ext-py line-numbers-mode"><pre v-pre class="language-python"><code>favorite_languages <span class="token operator">=</span> <span class="token punctuation">{</span> 
 <span class="token string">'jen'</span><span class="token punctuation">:</span> <span class="token string">'python'</span><span class="token punctuation">,</span> 
 <span class="token string">'sarah'</span><span class="token punctuation">:</span> <span class="token string">'c'</span><span class="token punctuation">,</span> 
 <span class="token string">'edward'</span><span class="token punctuation">:</span> <span class="token string">'ruby'</span><span class="token punctuation">,</span> 
 <span class="token string">'phil'</span><span class="token punctuation">:</span> <span class="token string">'python'</span><span class="token punctuation">,</span> 
 <span class="token punctuation">}</span> 
<span class="token keyword">for</span> name<span class="token punctuation">,</span> language <span class="token keyword">in</span> favorite_languages<span class="token punctuation">.</span>items<span class="token punctuation">(</span><span class="token punctuation">)</span><span class="token punctuation">:</span> 
   <span class="token keyword">print</span><span class="token punctuation">(</span>name<span class="token punctuation">.</span>title<span class="token punctuation">(</span><span class="token punctuation">)</span> <span class="token operator">+</span> <span class="token string">"'s favorite language is "</span> <span class="token operator">+</span>  language<span class="token punctuation">.</span>title<span class="token punctuation">(</span><span class="token punctuation">)</span> <span class="token operator">+</span> <span class="token string">"."</span><span class="token punctuation">)</span>
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><p>这些描述性名称能够让人非常轻松地明白print语句是做什么的。</p>
<div class="language-python ext-py line-numbers-mode"><pre v-pre class="language-python"><code>Jen's favorite language <span class="token keyword">is</span> Python<span class="token punctuation">.</span> 
Sarah's favorite language <span class="token keyword">is</span> C<span class="token punctuation">.</span> 
Phil's favorite language <span class="token keyword">is</span> Python<span class="token punctuation">.</span> 
Edward's favorite language <span class="token keyword">is</span> Ruby
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><p><a name="567d77ff"></a></p>
<h3 id="_6-3-2-遍历字典中的所有键" tabindex="-1"><a class="header-anchor" href="#_6-3-2-遍历字典中的所有键" aria-hidden="true">#</a> 6.3.2 遍历字典中的所有键</h3>
<p>在不需要使用字典中的值时，方法keys()很有用。下面来遍历字典favorite_languages，并将每个被调查者的名字都打印出来：</p>
<div class="language-python ext-py line-numbers-mode"><pre v-pre class="language-python"><code>favorite_languages <span class="token operator">=</span> <span class="token punctuation">{</span> 
 <span class="token string">'jen'</span><span class="token punctuation">:</span> <span class="token string">'python'</span><span class="token punctuation">,</span> 
 <span class="token string">'sarah'</span><span class="token punctuation">:</span> <span class="token string">'c'</span><span class="token punctuation">,</span> 
 <span class="token string">'edward'</span><span class="token punctuation">:</span> <span class="token string">'ruby'</span><span class="token punctuation">,</span> 
 <span class="token string">'phil'</span><span class="token punctuation">:</span> <span class="token string">'python'</span><span class="token punctuation">,</span> 
 <span class="token punctuation">}</span>
<span class="token keyword">for</span> name <span class="token keyword">in</span> favorite_languages<span class="token punctuation">.</span>keys<span class="token punctuation">(</span><span class="token punctuation">)</span><span class="token punctuation">:</span> 
  <span class="token keyword">print</span><span class="token punctuation">(</span>name<span class="token punctuation">.</span>title<span class="token punctuation">(</span><span class="token punctuation">)</span><span class="token punctuation">)</span>
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><div class="language-python ext-py line-numbers-mode"><pre v-pre class="language-python"><code>Jen 
Sarah 
Phil 
Edward
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><p>遍历字典时，会默认遍历所有的键，因此，如果将上述代码中的for name in favorite_ languages.keys():替换为for name in favorite_languages:，输出将不变。<br />在这种循环中，可使用当前键来访问与之相关联的值。下面来打印两条消息，指出两位朋友喜欢的语言。</p>
<div class="language-python ext-py line-numbers-mode"><pre v-pre class="language-python"><code>favorite_languages <span class="token operator">=</span> <span class="token punctuation">{</span> 
 <span class="token string">'jen'</span><span class="token punctuation">:</span> <span class="token string">'python'</span><span class="token punctuation">,</span> 
 <span class="token string">'sarah'</span><span class="token punctuation">:</span> <span class="token string">'c'</span><span class="token punctuation">,</span> 
 <span class="token string">'edward'</span><span class="token punctuation">:</span> <span class="token string">'ruby'</span><span class="token punctuation">,</span> 
 <span class="token string">'phil'</span><span class="token punctuation">:</span> <span class="token string">'python'</span><span class="token punctuation">,</span> 
 <span class="token punctuation">}</span> 
friends <span class="token operator">=</span> <span class="token punctuation">[</span><span class="token string">'phil'</span><span class="token punctuation">,</span> <span class="token string">'sarah'</span><span class="token punctuation">]</span> 
<span class="token keyword">for</span> name <span class="token keyword">in</span> favorite_languages<span class="token punctuation">.</span>keys<span class="token punctuation">(</span><span class="token punctuation">)</span><span class="token punctuation">:</span> 
   <span class="token keyword">print</span><span class="token punctuation">(</span>name<span class="token punctuation">.</span>title<span class="token punctuation">(</span><span class="token punctuation">)</span><span class="token punctuation">)</span> 
  <span class="token keyword">if</span> name <span class="token keyword">in</span> friends<span class="token punctuation">:</span> 
     <span class="token keyword">print</span><span class="token punctuation">(</span><span class="token string">" Hi "</span> <span class="token operator">+</span> name<span class="token punctuation">.</span>title<span class="token punctuation">(</span><span class="token punctuation">)</span> <span class="token operator">+</span> 
      <span class="token string">", I see your favorite language is "</span> <span class="token operator">+</span> 
      favorite_languages<span class="token punctuation">[</span>name<span class="token punctuation">]</span><span class="token punctuation">.</span>title<span class="token punctuation">(</span><span class="token punctuation">)</span> <span class="token operator">+</span> <span class="token string">"!"</span><span class="token punctuation">)</span>
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><p>每个人的名字都会被打印，但只对朋友打印特殊消息</p>
<div class="language-python ext-py line-numbers-mode"><pre v-pre class="language-python"><code>Edward 
Phil 
 Hi Phil<span class="token punctuation">,</span> I see your favorite language <span class="token keyword">is</span> Python! 
Sarah 
 Hi Sarah<span class="token punctuation">,</span> I see your favorite language <span class="token keyword">is</span> C! 
Jen
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><p>你还可以使用keys()确定某个人是否接受了调查。下面的代码确定Erin是否接受了调查：</p>
<div class="language-python ext-py line-numbers-mode"><pre v-pre class="language-python"><code>favorite_languages <span class="token operator">=</span> <span class="token punctuation">{</span> 
 <span class="token string">'jen'</span><span class="token punctuation">:</span> <span class="token string">'python'</span><span class="token punctuation">,</span> 
 <span class="token string">'sarah'</span><span class="token punctuation">:</span> <span class="token string">'c'</span><span class="token punctuation">,</span> 
 <span class="token string">'edward'</span><span class="token punctuation">:</span> <span class="token string">'ruby'</span><span class="token punctuation">,</span> 
 <span class="token string">'phil'</span><span class="token punctuation">:</span> <span class="token string">'python'</span><span class="token punctuation">,</span> 
 <span class="token punctuation">}</span> 
<span class="token keyword">if</span> <span class="token string">'erin'</span> <span class="token keyword">not</span> <span class="token keyword">in</span> favorite_languages<span class="token punctuation">.</span>keys<span class="token punctuation">(</span><span class="token punctuation">)</span><span class="token punctuation">:</span>
    <span class="token keyword">print</span><span class="token punctuation">(</span><span class="token string">"Erin, please take our poll!"</span><span class="token punctuation">)</span>
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><p>方法keys()并非只能用于遍历；实际上，它返回一个列表，其中包含字典中的所有键，因此1处的代码行只是核实'erin'是否包含在这个列表中。由于她并不包含在这个列表中，因此打印<br />一条消息，邀请她参加调查：</p>
<div class="language-python ext-py line-numbers-mode"><pre v-pre class="language-python"><code>Erin<span class="token punctuation">,</span> please take our poll!
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div></div></div><p><a name="3f459850"></a></p>
<h3 id="_6-3-3-按顺序遍历字典中的所有键" tabindex="-1"><a class="header-anchor" href="#_6-3-3-按顺序遍历字典中的所有键" aria-hidden="true">#</a> 6.3.3 按顺序遍历字典中的所有键</h3>
<p>字典总是明确地记录键和值之间的关联关系，但获取字典的元素时，获取顺序是不可预测的。这不是问题，因为通常你想要的只是获取与键相关联的正确的值。<br />要以特定的顺序返回元素，一种办法是在for循环中对返回的键进行排序。为此，可使用函数sorted()来获得按特定顺序排列的键列表的副本：</p>
<div class="language-python ext-py line-numbers-mode"><pre v-pre class="language-python"><code>favorite_languages <span class="token operator">=</span> <span class="token punctuation">{</span> 
 <span class="token string">'jen'</span><span class="token punctuation">:</span> <span class="token string">'python'</span><span class="token punctuation">,</span> 
 <span class="token string">'sarah'</span><span class="token punctuation">:</span> <span class="token string">'c'</span><span class="token punctuation">,</span> 
 <span class="token string">'edward'</span><span class="token punctuation">:</span> <span class="token string">'ruby'</span><span class="token punctuation">,</span> 
 <span class="token string">'phil'</span><span class="token punctuation">:</span> <span class="token string">'python'</span><span class="token punctuation">,</span> 
 <span class="token punctuation">}</span> 
<span class="token keyword">for</span> name <span class="token keyword">in</span> <span class="token builtin">sorted</span><span class="token punctuation">(</span>favorite_languages<span class="token punctuation">.</span>keys<span class="token punctuation">(</span><span class="token punctuation">)</span><span class="token punctuation">)</span><span class="token punctuation">:</span> 
 <span class="token keyword">print</span><span class="token punctuation">(</span>name<span class="token punctuation">.</span>title<span class="token punctuation">(</span><span class="token punctuation">)</span> <span class="token operator">+</span> <span class="token string">", thank you for taking the poll."</span><span class="token punctuation">)</span>
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><p>这条for语句类似于其他for语句，但对方法dictionary.keys()的结果调用了函数sorted()。这让Python列出字典中的所有键，并在遍历前对这个列表进行排序。输出表明，按顺序显示了所<br />有被调查者的名字：</p>
<div class="language-python ext-py line-numbers-mode"><pre v-pre class="language-python"><code>Edward<span class="token punctuation">,</span> thank you <span class="token keyword">for</span> taking the poll<span class="token punctuation">.</span> 
Jen<span class="token punctuation">,</span> thank you <span class="token keyword">for</span> taking the poll<span class="token punctuation">.</span> 
Phil<span class="token punctuation">,</span> thank you <span class="token keyword">for</span> taking the poll<span class="token punctuation">.</span> 
Sarah<span class="token punctuation">,</span> thank you <span class="token keyword">for</span> taking the poll<span class="token punctuation">.</span>
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><p><a name="ee6511ca"></a></p>
<h3 id="_6-3-4-遍历字典中的所有值" tabindex="-1"><a class="header-anchor" href="#_6-3-4-遍历字典中的所有值" aria-hidden="true">#</a> 6.3.4 遍历字典中的所有值</h3>
<p>如果你感兴趣的主要是字典包含的值，可使用方法values()，它返回一个值列表，而不包含任何键。</p>
<div class="language-python ext-py line-numbers-mode"><pre v-pre class="language-python"><code>favorite_languages <span class="token operator">=</span> <span class="token punctuation">{</span> 
 <span class="token string">'jen'</span><span class="token punctuation">:</span> <span class="token string">'python'</span><span class="token punctuation">,</span> 
 <span class="token string">'sarah'</span><span class="token punctuation">:</span> <span class="token string">'c'</span><span class="token punctuation">,</span> 
 <span class="token string">'edward'</span><span class="token punctuation">:</span> <span class="token string">'ruby'</span><span class="token punctuation">,</span> 
 <span class="token string">'phil'</span><span class="token punctuation">:</span> <span class="token string">'python'</span><span class="token punctuation">,</span>
 <span class="token punctuation">}</span> 
<span class="token keyword">print</span><span class="token punctuation">(</span><span class="token string">"The following languages have been mentioned:"</span><span class="token punctuation">)</span> 
<span class="token keyword">for</span> language <span class="token keyword">in</span> favorite_languages<span class="token punctuation">.</span>values<span class="token punctuation">(</span><span class="token punctuation">)</span><span class="token punctuation">:</span> 
  <span class="token keyword">print</span><span class="token punctuation">(</span>language<span class="token punctuation">.</span>title<span class="token punctuation">(</span><span class="token punctuation">)</span><span class="token punctuation">)</span>
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><p>这条for语句提取字典中的每个值，并将它们依次存储到变量language中。通过打印这些值，就获得了一个列表，其中包含被调查者选择的各种语言：</p>
<div class="language-python ext-py line-numbers-mode"><pre v-pre class="language-python"><code>The following languages have been mentioned<span class="token punctuation">:</span> 
Python 
C 
Python 
Ruby
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><p>为剔除重复项，可使用集合（set）。集合类似于列表，但每个元素都必须是独一无二的：</p>
<div class="language-python ext-py line-numbers-mode"><pre v-pre class="language-python"><code>favorite_languages <span class="token operator">=</span> <span class="token punctuation">{</span> 
 <span class="token string">'jen'</span><span class="token punctuation">:</span> <span class="token string">'python'</span><span class="token punctuation">,</span> 
 <span class="token string">'sarah'</span><span class="token punctuation">:</span> <span class="token string">'c'</span><span class="token punctuation">,</span> 
 <span class="token string">'edward'</span><span class="token punctuation">:</span> <span class="token string">'ruby'</span><span class="token punctuation">,</span> 
 <span class="token string">'phil'</span><span class="token punctuation">:</span> <span class="token string">'python'</span><span class="token punctuation">,</span> 
 <span class="token punctuation">}</span> 
<span class="token keyword">print</span><span class="token punctuation">(</span><span class="token string">"The following languages have been mentioned:"</span><span class="token punctuation">)</span> 
<span class="token keyword">for</span> language <span class="token keyword">in</span> <span class="token builtin">set</span><span class="token punctuation">(</span>favorite_languages<span class="token punctuation">.</span>values<span class="token punctuation">(</span><span class="token punctuation">)</span><span class="token punctuation">)</span><span class="token punctuation">:</span> 
  <span class="token keyword">print</span><span class="token punctuation">(</span>language<span class="token punctuation">.</span>title<span class="token punctuation">(</span><span class="token punctuation">)</span><span class="token punctuation">)</span>
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><p>结果是一个不重复的列表，其中列出了被调查者提及的所有语言：</p>
<div class="language-python ext-py line-numbers-mode"><pre v-pre class="language-python"><code>The following languages have been mentioned<span class="token punctuation">:</span> 
Python 
C 
Ruby
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><p><a name="644c0318"></a></p>
<h2 id="_6-4-嵌套" tabindex="-1"><a class="header-anchor" href="#_6-4-嵌套" aria-hidden="true">#</a> 6.4 嵌套</h2>
<p>有时候，需要将一系列字典存储在列表中，或将列表作为值存储在字典中，这称为嵌套。你可以在列表中嵌套字典、在字典中嵌套列表甚至在字典中嵌套字典。</p>
<p><a name="03a83e9e"></a></p>
<h3 id="_6-4-1-字典列表" tabindex="-1"><a class="header-anchor" href="#_6-4-1-字典列表" aria-hidden="true">#</a> 6.4.1 字典列表</h3>
<p>我们首先创建了三个字典，其中每个字典都表示一个外星人。</p>
<div class="language-python ext-py line-numbers-mode"><pre v-pre class="language-python"><code>alien_0 <span class="token operator">=</span> <span class="token punctuation">{</span><span class="token string">'color'</span><span class="token punctuation">:</span> <span class="token string">'green'</span><span class="token punctuation">,</span> <span class="token string">'points'</span><span class="token punctuation">:</span> <span class="token number">5</span><span class="token punctuation">}</span> 
alien_1 <span class="token operator">=</span> <span class="token punctuation">{</span><span class="token string">'color'</span><span class="token punctuation">:</span> <span class="token string">'yellow'</span><span class="token punctuation">,</span> <span class="token string">'points'</span><span class="token punctuation">:</span> <span class="token number">10</span><span class="token punctuation">}</span> 
alien_2 <span class="token operator">=</span> <span class="token punctuation">{</span><span class="token string">'color'</span><span class="token punctuation">:</span> <span class="token string">'red'</span><span class="token punctuation">,</span> <span class="token string">'points'</span><span class="token punctuation">:</span> <span class="token number">15</span><span class="token punctuation">}</span> 
aliens <span class="token operator">=</span> <span class="token punctuation">[</span>alien_0<span class="token punctuation">,</span> alien_1<span class="token punctuation">,</span> alien_2<span class="token punctuation">]</span> 
<span class="token keyword">for</span> alien <span class="token keyword">in</span> aliens<span class="token punctuation">:</span> 
   <span class="token keyword">print</span><span class="token punctuation">(</span>alien<span class="token punctuation">)</span>
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><div class="language-python ext-py line-numbers-mode"><pre v-pre class="language-python"><code><span class="token punctuation">{</span><span class="token string">'color'</span><span class="token punctuation">:</span> <span class="token string">'green'</span><span class="token punctuation">,</span> <span class="token string">'points'</span><span class="token punctuation">:</span> <span class="token number">5</span><span class="token punctuation">}</span> 
<span class="token punctuation">{</span><span class="token string">'color'</span><span class="token punctuation">:</span> <span class="token string">'yellow'</span><span class="token punctuation">,</span> <span class="token string">'points'</span><span class="token punctuation">:</span> <span class="token number">10</span><span class="token punctuation">}</span> 
<span class="token punctuation">{</span><span class="token string">'color'</span><span class="token punctuation">:</span> <span class="token string">'red'</span><span class="token punctuation">,</span> <span class="token string">'points'</span><span class="token punctuation">:</span> <span class="token number">15</span><span class="token punctuation">}</span>
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><p>我们使用range()生成了30个外星人：</p>
<div class="language-python ext-py line-numbers-mode"><pre v-pre class="language-python"><code><span class="token comment"># 创建一个用于存储外星人的空列表</span>
aliens <span class="token operator">=</span> <span class="token punctuation">[</span><span class="token punctuation">]</span> 
<span class="token comment"># 创建30个绿色的外星人</span>
<span class="token keyword">for</span> alien_number <span class="token keyword">in</span> <span class="token builtin">range</span><span class="token punctuation">(</span><span class="token number">30</span><span class="token punctuation">)</span><span class="token punctuation">:</span> 
new_alien <span class="token operator">=</span> <span class="token punctuation">{</span><span class="token string">'color'</span><span class="token punctuation">:</span> <span class="token string">'green'</span><span class="token punctuation">,</span> <span class="token string">'points'</span><span class="token punctuation">:</span> <span class="token number">5</span><span class="token punctuation">,</span> <span class="token string">'speed'</span><span class="token punctuation">:</span> <span class="token string">'slow'</span><span class="token punctuation">}</span> 
aliens<span class="token punctuation">.</span>append<span class="token punctuation">(</span>new_alien<span class="token punctuation">)</span> 
 <span class="token comment"># 显示前五个外星人</span>
<span class="token keyword">for</span> alien <span class="token keyword">in</span> aliens<span class="token punctuation">[</span><span class="token punctuation">:</span><span class="token number">5</span><span class="token punctuation">]</span><span class="token punctuation">:</span> 
   <span class="token keyword">print</span><span class="token punctuation">(</span>alien<span class="token punctuation">)</span> 
<span class="token keyword">print</span><span class="token punctuation">(</span><span class="token string">"..."</span><span class="token punctuation">)</span> 
<span class="token comment"># 显示创建了多少个外星人</span>
<span class="token keyword">print</span><span class="token punctuation">(</span><span class="token string">"Total number of aliens: "</span> <span class="token operator">+</span> <span class="token builtin">str</span><span class="token punctuation">(</span><span class="token builtin">len</span><span class="token punctuation">(</span>aliens<span class="token punctuation">)</span><span class="token punctuation">)</span><span class="token punctuation">)</span>
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><p>range()返回一系列数字，其唯一的用途是告诉Python我们要重复这个循环多少次。每次执行这个循环时，都创建一个外星人，并将其附加到列表aliens末尾。使用一个切片来打印前五个外星人。</p>
<div class="language-python ext-py line-numbers-mode"><pre v-pre class="language-python"><code><span class="token punctuation">{</span><span class="token string">'speed'</span><span class="token punctuation">:</span> <span class="token string">'slow'</span><span class="token punctuation">,</span> <span class="token string">'color'</span><span class="token punctuation">:</span> <span class="token string">'green'</span><span class="token punctuation">,</span> <span class="token string">'points'</span><span class="token punctuation">:</span> <span class="token number">5</span><span class="token punctuation">}</span> 
<span class="token punctuation">{</span><span class="token string">'speed'</span><span class="token punctuation">:</span> <span class="token string">'slow'</span><span class="token punctuation">,</span> <span class="token string">'color'</span><span class="token punctuation">:</span> <span class="token string">'green'</span><span class="token punctuation">,</span> <span class="token string">'points'</span><span class="token punctuation">:</span> <span class="token number">5</span><span class="token punctuation">}</span> 
<span class="token punctuation">{</span><span class="token string">'speed'</span><span class="token punctuation">:</span> <span class="token string">'slow'</span><span class="token punctuation">,</span> <span class="token string">'color'</span><span class="token punctuation">:</span> <span class="token string">'green'</span><span class="token punctuation">,</span> <span class="token string">'points'</span><span class="token punctuation">:</span> <span class="token number">5</span><span class="token punctuation">}</span> 
<span class="token punctuation">{</span><span class="token string">'speed'</span><span class="token punctuation">:</span> <span class="token string">'slow'</span><span class="token punctuation">,</span> <span class="token string">'color'</span><span class="token punctuation">:</span> <span class="token string">'green'</span><span class="token punctuation">,</span> <span class="token string">'points'</span><span class="token punctuation">:</span> <span class="token number">5</span><span class="token punctuation">}</span> 
<span class="token punctuation">{</span><span class="token string">'speed'</span><span class="token punctuation">:</span> <span class="token string">'slow'</span><span class="token punctuation">,</span> <span class="token string">'color'</span><span class="token punctuation">:</span> <span class="token string">'green'</span><span class="token punctuation">,</span> <span class="token string">'points'</span><span class="token punctuation">:</span> <span class="token number">5</span><span class="token punctuation">}</span> 
<span class="token punctuation">.</span><span class="token punctuation">.</span><span class="token punctuation">.</span> 
Total number of aliens<span class="token punctuation">:</span> <span class="token number">30</span>
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><p>这些外星人都具有相同的特征，但在Python看来，每个外星人都是独立的，这让我们能够独立地修改每个外星人。<br />必要时，我们可以使用for循环和if语句来修改某些外星人的颜色。</p>
<div class="language-python ext-py line-numbers-mode"><pre v-pre class="language-python"><code><span class="token comment"># 创建一个用于存储外星人的空列表</span>
aliens <span class="token operator">=</span> <span class="token punctuation">[</span><span class="token punctuation">]</span> 
<span class="token comment"># 创建30个绿色的外星人</span>
<span class="token keyword">for</span> alien_number <span class="token keyword">in</span> <span class="token builtin">range</span> <span class="token punctuation">(</span><span class="token number">0</span><span class="token punctuation">,</span><span class="token number">30</span><span class="token punctuation">)</span><span class="token punctuation">:</span>
   new_alien <span class="token operator">=</span> <span class="token punctuation">{</span><span class="token string">'color'</span><span class="token punctuation">:</span> <span class="token string">'green'</span><span class="token punctuation">,</span> <span class="token string">'points'</span><span class="token punctuation">:</span> <span class="token number">5</span><span class="token punctuation">,</span> <span class="token string">'speed'</span><span class="token punctuation">:</span> <span class="token string">'slow'</span><span class="token punctuation">}</span> 
   aliens<span class="token punctuation">.</span>append<span class="token punctuation">(</span>new_alien<span class="token punctuation">)</span> 
 
<span class="token keyword">for</span> alien <span class="token keyword">in</span> aliens<span class="token punctuation">[</span><span class="token number">0</span><span class="token punctuation">:</span><span class="token number">3</span><span class="token punctuation">]</span><span class="token punctuation">:</span> 
  <span class="token keyword">if</span> alien<span class="token punctuation">[</span><span class="token string">'color'</span><span class="token punctuation">]</span> <span class="token operator">==</span> <span class="token string">'green'</span><span class="token punctuation">:</span> 
   alien<span class="token punctuation">[</span><span class="token string">'color'</span><span class="token punctuation">]</span> <span class="token operator">=</span> <span class="token string">'yellow'</span> 
   alien<span class="token punctuation">[</span><span class="token string">'speed'</span><span class="token punctuation">]</span> <span class="token operator">=</span> <span class="token string">'medium'</span> 
   alien<span class="token punctuation">[</span><span class="token string">'points'</span><span class="token punctuation">]</span> <span class="token operator">=</span> <span class="token number">10</span> 
 
<span class="token comment"># 显示前五个外星人</span>
<span class="token keyword">for</span> alien <span class="token keyword">in</span> aliens<span class="token punctuation">[</span><span class="token number">0</span><span class="token punctuation">:</span><span class="token number">5</span><span class="token punctuation">]</span><span class="token punctuation">:</span> 
  <span class="token keyword">print</span><span class="token punctuation">(</span>alien<span class="token punctuation">)</span> 
<span class="token keyword">print</span><span class="token punctuation">(</span><span class="token string">"..."</span><span class="token punctuation">)</span>
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><p>鉴于我们要修改前三个外星人，需要遍历一个只包含这些外星人的切片。当前，所有外星人都是绿色的，但情况并非总是如此，因此我们编写了一条if语句来确保只修改绿色外星人。如果外星人是绿色的，我们就将其颜色改为'yellow'，将其速度改为'medium'，并将其点数改为10，如下面的输出所示：</p>
<div class="language-python ext-py line-numbers-mode"><pre v-pre class="language-python"><code><span class="token punctuation">{</span><span class="token string">'speed'</span><span class="token punctuation">:</span> <span class="token string">'medium'</span><span class="token punctuation">,</span> <span class="token string">'color'</span><span class="token punctuation">:</span> <span class="token string">'yellow'</span><span class="token punctuation">,</span> <span class="token string">'points'</span><span class="token punctuation">:</span> <span class="token number">10</span><span class="token punctuation">}</span> 
<span class="token punctuation">{</span><span class="token string">'speed'</span><span class="token punctuation">:</span> <span class="token string">'medium'</span><span class="token punctuation">,</span> <span class="token string">'color'</span><span class="token punctuation">:</span> <span class="token string">'yellow'</span><span class="token punctuation">,</span> <span class="token string">'points'</span><span class="token punctuation">:</span> <span class="token number">10</span><span class="token punctuation">}</span> 
<span class="token punctuation">{</span><span class="token string">'speed'</span><span class="token punctuation">:</span> <span class="token string">'medium'</span><span class="token punctuation">,</span> <span class="token string">'color'</span><span class="token punctuation">:</span> <span class="token string">'yellow'</span><span class="token punctuation">,</span> <span class="token string">'points'</span><span class="token punctuation">:</span> <span class="token number">10</span><span class="token punctuation">}</span> 
<span class="token punctuation">{</span><span class="token string">'speed'</span><span class="token punctuation">:</span> <span class="token string">'slow'</span><span class="token punctuation">,</span> <span class="token string">'color'</span><span class="token punctuation">:</span> <span class="token string">'green'</span><span class="token punctuation">,</span> <span class="token string">'points'</span><span class="token punctuation">:</span> <span class="token number">5</span><span class="token punctuation">}</span> 
<span class="token punctuation">{</span><span class="token string">'speed'</span><span class="token punctuation">:</span> <span class="token string">'slow'</span><span class="token punctuation">,</span> <span class="token string">'color'</span><span class="token punctuation">:</span> <span class="token string">'green'</span><span class="token punctuation">,</span> <span class="token string">'points'</span><span class="token punctuation">:</span> <span class="token number">5</span><span class="token punctuation">}</span> 
<span class="token punctuation">.</span><span class="token punctuation">.</span><span class="token punctuation">.</span>
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><p>你可以进一步扩展这个循环，在其中添加一个elif代码块，将黄色外星人改为移动速度快且值15个点的红色外星人，如下所示（这里只列出了循环，而没有列出整个程序）：</p>
<div class="language-python ext-py line-numbers-mode"><pre v-pre class="language-python"><code><span class="token keyword">for</span> alien <span class="token keyword">in</span> aliens<span class="token punctuation">[</span><span class="token number">0</span><span class="token punctuation">:</span><span class="token number">3</span><span class="token punctuation">]</span><span class="token punctuation">:</span> 
  <span class="token keyword">if</span> alien<span class="token punctuation">[</span><span class="token string">'color'</span><span class="token punctuation">]</span> <span class="token operator">==</span> <span class="token string">'green'</span><span class="token punctuation">:</span> 
    alien<span class="token punctuation">[</span><span class="token string">'color'</span><span class="token punctuation">]</span> <span class="token operator">=</span> <span class="token string">'yellow'</span> 
    alien<span class="token punctuation">[</span><span class="token string">'speed'</span><span class="token punctuation">]</span> <span class="token operator">=</span> <span class="token string">'medium'</span> 
    alien<span class="token punctuation">[</span><span class="token string">'points'</span><span class="token punctuation">]</span> <span class="token operator">=</span> <span class="token number">10</span> 
  <span class="token keyword">elif</span> alien<span class="token punctuation">[</span><span class="token string">'color'</span><span class="token punctuation">]</span> <span class="token operator">==</span> <span class="token string">'yellow'</span><span class="token punctuation">:</span> 
    alien<span class="token punctuation">[</span><span class="token string">'color'</span><span class="token punctuation">]</span> <span class="token operator">=</span> <span class="token string">'red'</span> 
    alien<span class="token punctuation">[</span><span class="token string">'speed'</span><span class="token punctuation">]</span> <span class="token operator">=</span> <span class="token string">'fast'</span> 
    alien<span class="token punctuation">[</span><span class="token string">'points'</span><span class="token punctuation">]</span> <span class="token operator">=</span> <span class="token number">15</span>
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><p><a name="72bfa1ef"></a></p>
<h3 id="_6-4-2-在字典中存储列表" tabindex="-1"><a class="header-anchor" href="#_6-4-2-在字典中存储列表" aria-hidden="true">#</a> 6.4.2 在字典中存储列表</h3>
<p>有时候，需要将列表存储在字典中，而不是将字典存储在列表中。<br />在下面的示例中，存储了比萨的两方面信息：外皮类型和配料列表。其中的配料列表是一个与键'toppings'相关联的值。要访问该列表，我们使用字典名和键'toppings'，就像访问字典中<br />的其他值一样。这将返回一个配料列表，而不是单个值：</p>
<div class="language-python ext-py line-numbers-mode"><pre v-pre class="language-python"><code> <span class="token comment"># 存储所点比萨的信息</span>
 pizza <span class="token operator">=</span> <span class="token punctuation">{</span> 
 <span class="token string">'crust'</span><span class="token punctuation">:</span> <span class="token string">'thick'</span><span class="token punctuation">,</span> 
 <span class="token string">'toppings'</span><span class="token punctuation">:</span> <span class="token punctuation">[</span><span class="token string">'mushrooms'</span><span class="token punctuation">,</span> <span class="token string">'extra cheese'</span><span class="token punctuation">]</span><span class="token punctuation">,</span> 
 <span class="token punctuation">}</span> 
<span class="token comment"># 概述所点的比萨</span>
 <span class="token keyword">print</span><span class="token punctuation">(</span><span class="token string">"You ordered a "</span> <span class="token operator">+</span> pizza<span class="token punctuation">[</span><span class="token string">'crust'</span><span class="token punctuation">]</span> <span class="token operator">+</span> <span class="token string">"-crust pizza "</span> <span class="token operator">+</span> 
  <span class="token string">"with the following toppings:"</span><span class="token punctuation">)</span> 
 <span class="token keyword">for</span> topping <span class="token keyword">in</span> pizza<span class="token punctuation">[</span><span class="token string">'toppings'</span><span class="token punctuation">]</span><span class="token punctuation">:</span> 
   <span class="token keyword">print</span><span class="token punctuation">(</span><span class="token string">"\t"</span> <span class="token operator">+</span> topping<span class="token punctuation">)</span>
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><div class="language-python ext-py line-numbers-mode"><pre v-pre class="language-python"><code>You ordered a thick<span class="token operator">-</span>crust pizza <span class="token keyword">with</span> the following toppings<span class="token punctuation">:</span> 
 mushrooms 
 extra cheese
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><p>每当需要在字典中将一个键关联到多个值时，都可以在字典中嵌套一个列表。</p>
<div class="language-python ext-py line-numbers-mode"><pre v-pre class="language-python"><code>favorite_languages <span class="token operator">=</span> <span class="token punctuation">{</span> 
 <span class="token string">'jen'</span><span class="token punctuation">:</span> <span class="token punctuation">[</span><span class="token string">'python'</span><span class="token punctuation">,</span> <span class="token string">'ruby'</span><span class="token punctuation">]</span><span class="token punctuation">,</span> 
 <span class="token string">'sarah'</span><span class="token punctuation">:</span> <span class="token punctuation">[</span><span class="token string">'c'</span><span class="token punctuation">]</span><span class="token punctuation">,</span> 
 <span class="token string">'edward'</span><span class="token punctuation">:</span> <span class="token punctuation">[</span><span class="token string">'ruby'</span><span class="token punctuation">,</span> <span class="token string">'go'</span><span class="token punctuation">]</span><span class="token punctuation">,</span> 
 <span class="token string">'phil'</span><span class="token punctuation">:</span> <span class="token punctuation">[</span><span class="token string">'python'</span><span class="token punctuation">,</span> <span class="token string">'haskell'</span><span class="token punctuation">]</span><span class="token punctuation">,</span> 
 <span class="token punctuation">}</span>
<span class="token keyword">for</span> name<span class="token punctuation">,</span> languages <span class="token keyword">in</span> favorite_languages<span class="token punctuation">.</span>items<span class="token punctuation">(</span><span class="token punctuation">)</span><span class="token punctuation">:</span> 
   <span class="token keyword">print</span><span class="token punctuation">(</span><span class="token string">"\n"</span> <span class="token operator">+</span> name<span class="token punctuation">.</span>title<span class="token punctuation">(</span><span class="token punctuation">)</span> <span class="token operator">+</span> <span class="token string">"'s favorite languages are:"</span><span class="token punctuation">)</span> 
<span class="token keyword">for</span> language <span class="token keyword">in</span> languages<span class="token punctuation">:</span> 
  <span class="token keyword">print</span><span class="token punctuation">(</span><span class="token string">"\t"</span> <span class="token operator">+</span> language<span class="token punctuation">.</span>title<span class="token punctuation">(</span><span class="token punctuation">)</span><span class="token punctuation">)</span>
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><div class="language-python ext-py line-numbers-mode"><pre v-pre class="language-python"><code>Jen's favorite languages are<span class="token punctuation">:</span> 
 Python 
 Ruby 
Sarah's favorite languages are<span class="token punctuation">:</span> 
 C 
Phil's favorite languages are<span class="token punctuation">:</span> 
 Python 
 Haskell 
Edward's favorite languages are<span class="token punctuation">:</span> 
 Ruby 
 Go
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><p><a name="ee1b9e2a"></a></p>
<h3 id="_6-4-3-在字典中存储字典" tabindex="-1"><a class="header-anchor" href="#_6-4-3-在字典中存储字典" aria-hidden="true">#</a> 6.4.3 在字典中存储字典</h3>
<p>可在字典中嵌套字典，但这样做时，代码可能很快复杂起来。</p>
<div class="language-python ext-py line-numbers-mode"><pre v-pre class="language-python"><code>users <span class="token operator">=</span> <span class="token punctuation">{</span> 
 <span class="token string">'aeinstein'</span><span class="token punctuation">:</span> <span class="token punctuation">{</span> 
 <span class="token string">'first'</span><span class="token punctuation">:</span> <span class="token string">'albert'</span><span class="token punctuation">,</span> 
 <span class="token string">'last'</span><span class="token punctuation">:</span> <span class="token string">'einstein'</span><span class="token punctuation">,</span> 
 <span class="token string">'location'</span><span class="token punctuation">:</span> <span class="token string">'princeton'</span><span class="token punctuation">,</span> 
 <span class="token punctuation">}</span><span class="token punctuation">,</span> 
 <span class="token string">'mcurie'</span><span class="token punctuation">:</span> <span class="token punctuation">{</span> 
 <span class="token string">'first'</span><span class="token punctuation">:</span> <span class="token string">'marie'</span><span class="token punctuation">,</span> 
 <span class="token string">'last'</span><span class="token punctuation">:</span> <span class="token string">'curie'</span><span class="token punctuation">,</span> 
 <span class="token string">'location'</span><span class="token punctuation">:</span> <span class="token string">'paris'</span><span class="token punctuation">,</span> 
 <span class="token punctuation">}</span><span class="token punctuation">,</span> 
 <span class="token punctuation">}</span> 
<span class="token keyword">for</span> username<span class="token punctuation">,</span> user_info <span class="token keyword">in</span> users<span class="token punctuation">.</span>items<span class="token punctuation">(</span><span class="token punctuation">)</span><span class="token punctuation">:</span> 
   <span class="token keyword">print</span><span class="token punctuation">(</span><span class="token string">"\nUsername: "</span> <span class="token operator">+</span> username<span class="token punctuation">)</span> 
   full_name <span class="token operator">=</span> user_info<span class="token punctuation">[</span><span class="token string">'first'</span><span class="token punctuation">]</span> <span class="token operator">+</span> <span class="token string">" "</span> <span class="token operator">+</span> user_info<span class="token punctuation">[</span><span class="token string">'last'</span><span class="token punctuation">]</span> 
   location <span class="token operator">=</span> user_info<span class="token punctuation">[</span><span class="token string">'location'</span><span class="token punctuation">]</span> 
   <span class="token keyword">print</span><span class="token punctuation">(</span><span class="token string">"\tFull name: "</span> <span class="token operator">+</span> full_name<span class="token punctuation">.</span>title<span class="token punctuation">(</span><span class="token punctuation">)</span><span class="token punctuation">)</span> 
   <span class="token keyword">print</span><span class="token punctuation">(</span><span class="token string">"\tLocation: "</span> <span class="token operator">+</span> location<span class="token punctuation">.</span>title<span class="token punctuation">(</span><span class="token punctuation">)</span><span class="token punctuation">)</span>
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><p>我们首先定义了一个名为users的字典，其中包含两个键：用户名'aeinstein'和'mcurie'；与每个键相关联的值都是一个字典，其中包含用户的名、姓和居住地。</p>
<div class="language-python ext-py line-numbers-mode"><pre v-pre class="language-python"><code>Username<span class="token punctuation">:</span> aeinstein 
  Full name<span class="token punctuation">:</span> Albert Einstein 
  Location<span class="token punctuation">:</span> Princeton 
Username<span class="token punctuation">:</span> mcurie 
  Full name<span class="token punctuation">:</span> Marie Curie 
  Location<span class="token punctuation">:</span> Paris
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><p>请注意，表示每位用户的字典的结构都相同，虽然Python并没有这样的要求，但这使得嵌套的字典处理起来更容易。倘若表示每位用户的字典都包含不同的键，for循环内部的代码将更复杂。</p>
<p><a name="0783ec21"></a></p>
<h2 id="_6-5-小结" tabindex="-1"><a class="header-anchor" href="#_6-5-小结" aria-hidden="true">#</a> 6.5 小结</h2>
<p>在本章中，你学习了：如何定义字典，以及如何使用存储在字典中的信息；如何访问和修改字典中的元素，以及如何遍历字典中的所有信息；如何遍历字典中所有的键值对、所有的键和所有的值；如何在列表中嵌套字典、在字典中嵌套列表以及在字典中嵌套字典。<br />在下一章中，你将学习while循环以及如何从用户那里获取输入。这是激动人心的一章，让你知道如何将程序变成交互性的——能够对用户输入作出响应。</p>
</div></template>


